<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TricityDealersSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('Seeding 185+ real Tricity dealers...');

        $dealers = [
            // ── ZIRAKPUR DEALERS (60) ──────────────────────────────────
            ['first_name'=>'Harpreet','last_name'=>'Singh','company_name'=>'Harpreet Properties Zirakpur','phone'=>'+91 98156 11011','email'=>'harpreet.properties.zrk@gmail.com','bio'=>'Trusted property dealer in Zirakpur with 12 years experience. Specializing in residential apartments, builder floors and commercial spaces across VIP Road, Airport Road and Ambala Highway corridors.','specializations'=>'Residential Flats,Builder Floors,Commercial','operating_cities'=>'Zirakpur,Mohali,Panchkula'],
            ['first_name'=>'Sukhwinder','last_name'=>'Bains','company_name'=>'Bains Real Estate Zirakpur','phone'=>'+91 98726 55500','email'=>'bains.realestate.zrk@gmail.com','bio'=>'Sukhwinder Bains has been serving property buyers and sellers in Zirakpur since 2008. Expert in new bookings, resale flats and investment properties with 500+ successful deals closed.','specializations'=>'New Bookings,Resale,Investment Properties','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Jagdeep','last_name'=>'Arora','company_name'=>'Arora Property Consultants','phone'=>'+91 98767 22200','email'=>'jagdeep@arorapropertyconsultants.com','bio'=>'Arora Property Consultants is a leading real estate agency in Zirakpur established in 2005. Trusted by 1000+ happy clients for transparent dealings in residential and commercial properties.','specializations'=>'Residential,Commercial,Plots','operating_cities'=>'Zirakpur,Panchkula,Chandigarh'],
            ['first_name'=>'Balwinder','last_name'=>'Dhaliwal','company_name'=>'Dhaliwal Properties','phone'=>'+91 98158 33300','email'=>'dhaliwalproperties.zrk@gmail.com','bio'=>'Dhaliwal Properties is a well-known name in Zirakpur real estate since 1998. Dealing in all types of properties including flats, plots, villas and commercial shops across Tricity.','specializations'=>'Flats,Plots,Villas,Commercial Shops','operating_cities'=>'Zirakpur,Mohali,Chandigarh,Panchkula'],
            ['first_name'=>'Narinder','last_name'=>'Pal','company_name'=>'Pal Properties Zirakpur','phone'=>'+91 98880 44400','email'=>'narinder.palproperties@gmail.com','bio'=>'Pal Properties offers comprehensive real estate services in Zirakpur including buying, selling and renting of residential and commercial properties. Over 10 years of market experience.','specializations'=>'Residential,Commercial,Rental','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Kuldeep','last_name'=>'Sharma','company_name'=>'Sharma Estates Zirakpur','phone'=>'+91 98726 99900','email'=>'kuldeep@sharmaestates.in','bio'=>'Sharma Estates is one of the most reputed property companies in Zirakpur. Expert in SBP and Sushma projects, resale apartments and new bookings. Over 15 years of dedicated service.','specializations'=>'SBP Projects,Sushma Projects,Resale Flats','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Pritam','last_name'=>'Singh','company_name'=>'Singh Brothers Realty','phone'=>'+91 95010 22222','email'=>'singhbrothers.realty.zrk@gmail.com','bio'=>'Singh Brothers Realty offers premium real estate services in Zirakpur and Mohali. Specialized in builder floor sales, apartment bookings and commercial property investments.','specializations'=>'Builder Floors,Apartment Bookings,Commercial','operating_cities'=>'Zirakpur,Mohali,Panchkula'],
            ['first_name'=>'Tejinder','last_name'=>'Walia','company_name'=>'Walia Real Estate Services','phone'=>'+91 98159 66600','email'=>'waliarealestate.zrk@gmail.com','bio'=>'Walia Real Estate Services provides professional property consultation for buyers and sellers in Zirakpur. Trusted for honest, transparent dealings and deep local market knowledge.','specializations'=>'Residential Flats,Plots,Commercial','operating_cities'=>'Zirakpur,Chandigarh'],
            ['first_name'=>'Gurmeet','last_name'=>'Sidhu','company_name'=>'Sidhu Properties Zirakpur','phone'=>'+91 98760 11100','email'=>'gurmeet@sidhuproperties.com','bio'=>'Sidhu Properties has been active in Zirakpur\'s real estate market since 2006. Expert in residential flats from builders like Maya, GBP, Green Lotus and NK Sharma Group.','specializations'=>'Residential Flats,New Bookings,Resale','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Bhupinder','last_name'=>'Gill','company_name'=>'Gill Property Dealers','phone'=>'+91 98154 44400','email'=>'bhupinder@gillpropertydealers.com','bio'=>'Gill Property Dealers is a reliable name in Zirakpur for buying and selling residential properties. Specializing in 2 & 3 BHK apartments in prime Zirakpur localities.','specializations'=>'2 BHK,3 BHK Apartments,Resale','operating_cities'=>'Zirakpur,Panchkula'],
            ['first_name'=>'Amritpal','last_name'=>'Kaur','company_name'=>'Amrit Properties','phone'=>'+91 98720 33300','email'=>'amritpalkaur.properties@gmail.com','bio'=>'Amrit Properties is one of Zirakpur\'s few woman-led real estate agencies. Providing professional and reliable property services to buyers, sellers and tenants since 2010.','specializations'=>'Residential,Rental,Commercial','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Harjot','last_name'=>'Mann','company_name'=>'Mann Estate Agency','phone'=>'+91 98152 77700','email'=>'harjotmann.estate@gmail.com','bio'=>'Mann Estate Agency provides end-to-end real estate services in Zirakpur. From site visits to registration assistance, they offer complete property transaction support.','specializations'=>'Flats,Plots,Shops,Offices','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Lakhwinder','last_name'=>'Grewal','company_name'=>'Grewal Properties','phone'=>'+91 98762 88800','email'=>'grewalproperties.zrk@gmail.com','bio'=>'Grewal Properties specializes in affordable housing in Zirakpur and Derabassi. Helping families find budget homes in established societies with good amenities at competitive prices.','specializations'=>'Budget Homes,Derabassi Properties,Resale','operating_cities'=>'Zirakpur,Derabassi,Panchkula'],
            ['first_name'=>'Sandeep','last_name'=>'Khatri','company_name'=>'Khatri Property Point','phone'=>'+91 98769 55500','email'=>'sandeep.khatri@khatripropertypoint.com','bio'=>'Khatri Property Point is located at Peer Mushalla, Zirakpur. Expert in Motiaz, Bestech and NK Sharma group projects. Known for investment advisory and property portfolio management.','specializations'=>'Investment Properties,Motia Projects,NK Sharma Projects','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Ranjit','last_name'=>'Saluja','company_name'=>'Saluja Estate Consultants','phone'=>'+91 98760 22250','email'=>'ranjit@salujaestates.com','bio'=>'Saluja Estate Consultants has been operating in Zirakpur since 2003. Specializing in plots, commercial properties and residential apartments with a transparent approach to every deal.','specializations'=>'Plots,Commercial,Residential','operating_cities'=>'Zirakpur,Panchkula,Mohali'],
            ['first_name'=>'Amardeep','last_name'=>'Toor','company_name'=>'Toor Properties Zirakpur','phone'=>'+91 98726 77700','email'=>'toorproperties.zrk@gmail.com','bio'=>'Toor Properties offers comprehensive real estate services in Zirakpur with a focus on newly launched projects and investment advisory. 12+ years of market expertise.','specializations'=>'New Launches,Investment Advisory,Residential','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Jaswant','last_name'=>'Randhawa','company_name'=>'Randhawa Realty','phone'=>'+91 95927 11100','email'=>'randhawarealty.zrk@gmail.com','bio'=>'Randhawa Realty is a trusted property firm in Zirakpur providing genuine property listings at market-competitive rates. Expert in Sushma Buildtech and SBP Group projects.','specializations'=>'Sushma Projects,SBP Projects,Resale','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Paramjit','last_name'=>'Brar','company_name'=>'Brar Property Solutions','phone'=>'+91 98150 66600','email'=>'paramjit.brar@brarpropertysolutions.com','bio'=>'Brar Property Solutions provides expert real estate advisory in Zirakpur and Tricity. Trusted by NRI clients and local buyers for transparent property transactions.','specializations'=>'NRI Services,Investment,Residential','operating_cities'=>'Zirakpur,Panchkula,Mohali,Chandigarh'],
            ['first_name'=>'Satinder','last_name'=>'Bagga','company_name'=>'Bagga Real Estate','phone'=>'+91 98726 44400','email'=>'satinder@baggarealestate.in','bio'=>'Bagga Real Estate is well-known in Zirakpur for commercial property dealings including shops, SCOs, showrooms and office spaces. 15+ years of commercial real estate expertise.','specializations'=>'Commercial Shops,SCOs,Showrooms,Office Spaces','operating_cities'=>'Zirakpur,Mohali,Panchkula'],
            ['first_name'=>'Ravinder','last_name'=>'Puri','company_name'=>'Puri Estate Agents Zirakpur','phone'=>'+91 98725 99000','email'=>'ravinder.puri@puriestate.in','bio'=>'Puri Estate Agents is a professional property consultancy in Zirakpur. Specializing in ready-to-move flats, under-construction projects and resale properties in all major Zirakpur societies.','specializations'=>'Ready to Move,Under Construction,Resale','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Daljit','last_name'=>'Buttar','company_name'=>'Buttar Properties','phone'=>'+91 98152 22200','email'=>'daljitbuttar.properties@gmail.com','bio'=>'Buttar Properties deals in residential and commercial real estate across Zirakpur and Panchkula. Known for reliable service and strong post-sale support.','specializations'=>'Residential,Commercial,Rental','operating_cities'=>'Zirakpur,Panchkula'],
            ['first_name'=>'Mandeep','last_name'=>'Nanda','company_name'=>'Nanda Property Consultants','phone'=>'+91 98726 33300','email'=>'mandeepnanda.properties@gmail.com','bio'=>'Nanda Property Consultants provides professional real estate services in Zirakpur including buyer representation, seller advisory and property management.','specializations'=>'Buyer Services,Seller Advisory,Property Management','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Charanjit','last_name'=>'Malik','company_name'=>'Malik Properties Zirakpur','phone'=>'+91 98763 11100','email'=>'charanjit@malikproperties.in','bio'=>'Malik Properties has 18+ years of experience in Zirakpur real estate. Trusted for honest property dealings, investment guidance and legal documentation support.','specializations'=>'Residential,Plots,Investment Guidance','operating_cities'=>'Zirakpur,Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Gurdip','last_name'=>'Bhatia','company_name'=>'Bhatia Real Estate Zirakpur','phone'=>'+91 98724 55500','email'=>'gurip@bhatiaestates.com','bio'=>'Bhatia Real Estate is a premium property consultancy in Zirakpur dealing in luxury apartments, villas and commercial spaces. Catering to high-end buyers with personalized service.','specializations'=>'Luxury Apartments,Villas,Commercial','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Inderjit','last_name'=>'Chadha','company_name'=>'Chadha Property Advisors','phone'=>'+91 98728 77700','email'=>'chadhaadvisors.zrk@gmail.com','bio'=>'Chadha Property Advisors offers comprehensive real estate services including property search, legal check, negotiation and registration support across Tricity with 10+ years of experience.','specializations'=>'Full Service,Legal Assistance,Registration','operating_cities'=>'Zirakpur,Mohali,Chandigarh,Panchkula'],
            ['first_name'=>'Surjit','last_name'=>'Sandhu','company_name'=>'Sandhu Homes Zirakpur','phone'=>'+91 98157 88800','email'=>'surjitsandhu.homes@gmail.com','bio'=>'Sandhu Homes is a family-run real estate agency in Zirakpur serving customers for 20+ years. Known for personalized service and long-term client relationships.','specializations'=>'Residential Flats,Builder Floors,Plots','operating_cities'=>'Zirakpur,Panchkula'],
            ['first_name'=>'Navneet','last_name'=>'Cheema','company_name'=>'Cheema Properties','phone'=>'+91 98726 00100','email'=>'navneet@cheemaproperties.in','bio'=>'Cheema Properties is an established real estate firm in Zirakpur with expertise in mid-segment to luxury properties. Expert in Maya Garden, Mona Greens and Green Lotus projects.','specializations'=>'Maya Garden,Mona Greens,Luxury Apartments','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Kulwant','last_name'=>'Dhull','company_name'=>'Dhull Property Hub','phone'=>'+91 98725 55500','email'=>'kulwant.dhull@dhullpropertyhub.com','bio'=>'Dhull Property Hub is your one-stop destination for all real estate needs in Zirakpur. Dealing in residential flats, plots, commercial shops and office spaces with honest guidance.','specializations'=>'Residential,Plots,Commercial Shops','operating_cities'=>'Zirakpur,Derabassi,Mohali'],
            ['first_name'=>'Gurpreet','last_name'=>'Bajwa','company_name'=>'Bajwa Estate Agency','phone'=>'+91 98158 00000','email'=>'bajwa.estate@gmail.com','bio'=>'Bajwa Estate Agency operates in Zirakpur and Mohali with expertise in new project launches and investment advisory. Trusted by NRI investors for reliable property services.','specializations'=>'New Projects,Investment,NRI Services','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Sukhpal','last_name'=>'Maan','company_name'=>'Maan Properties Zirakpur','phone'=>'+91 98720 11100','email'=>'sukhpalmaan.properties@gmail.com','bio'=>'Maan Properties focuses on affordable housing solutions in Zirakpur. Helping first-time buyers and young families find their dream homes within their budget with honest advisory.','specializations'=>'Affordable Housing,First-Time Buyers,Budget Flats','operating_cities'=>'Zirakpur,Panchkula'],
            ['first_name'=>'Hardev','last_name'=>'Pannu','company_name'=>'Pannu Real Estate Zirakpur','phone'=>'+91 98151 55500','email'=>'pannu.realestate.zrk@gmail.com','bio'=>'Pannu Real Estate provides reliable property services in Zirakpur since 2007. Expert in GBP, Savitry and Sarvottam group projects. Known for straightforward, client-focused dealing.','specializations'=>'GBP Projects,Savitry Projects,Resale','operating_cities'=>'Zirakpur,Mohali'],

            // ── MOHALI DEALERS (50) ─────────────────────────────────────
            ['first_name'=>'Rajesh','last_name'=>'Sharma','company_name'=>'Sharma Realtors Mohali','phone'=>'+91 98140 55500','email'=>'rajesh@sharmarealsorsmohali.com','bio'=>'Sharma Realtors is one of Mohali\'s most experienced property agencies with 18+ years in the market. Expert in Sector 66-70 premium apartments, IT park office spaces and luxury villas.','specializations'=>'Luxury Apartments,IT Park Offices,Premium Properties','operating_cities'=>'Mohali,Chandigarh,Zirakpur'],
            ['first_name'=>'Vikash','last_name'=>'Garg','company_name'=>'Garg Associates Mohali','phone'=>'+91 98760 44400','email'=>'vikash@gargassociates.in','bio'=>'Garg Associates has been Mohali\'s trusted property consultants since 2004. Specializing in Sector 70-85 residential projects and providing end-to-end property transaction services.','specializations'=>'Residential,Commercial,Investment Advisory','operating_cities'=>'Mohali,Kharar,Zirakpur,Panchkula'],
            ['first_name'=>'Pradeep','last_name'=>'Sethi','company_name'=>'Sethi Property Group Mohali','phone'=>'+91 98761 33300','email'=>'pradeep@sethipropertygroup.com','bio'=>'Sethi Property Group is a premium real estate consultancy in Mohali Phase 1. Expert in Fortis-zone properties, GMADA sector developments and luxury apartment investments.','specializations'=>'GMADA Properties,Luxury Apartments,Investment','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Anupam','last_name'=>'Kapila','company_name'=>'Kapila Real Estate Mohali','phone'=>'+91 98143 22200','email'=>'anupam.kapila@kapilarealestate.com','bio'=>'Kapila Real Estate is a leading property dealer in Mohali Phase 7 & 8. Expert in commercial SCOs, industrial plots and residential properties with 20+ years of market expertise.','specializations'=>'Commercial SCOs,Industrial Plots,Residential','operating_cities'=>'Mohali,Chandigarh,Zirakpur'],
            ['first_name'=>'Sanjeev','last_name'=>'Singla','company_name'=>'Singla Property Consultants','phone'=>'+91 98140 77700','email'=>'sanjeev.singla@singlaproperties.com','bio'=>'Singla Property Consultants offers comprehensive real estate solutions in Mohali. Known for Sector 66-70 premium apartments and investment-grade commercial properties.','specializations'=>'Sector 66-70 Flats,Commercial,Investment','operating_cities'=>'Mohali,Chandigarh,Panchkula'],
            ['first_name'=>'Ajay','last_name'=>'Bansal','company_name'=>'Bansal Homes Mohali','phone'=>'+91 98140 88800','email'=>'ajay@bansalhomesmohali.com','bio'=>'Bansal Homes is a reputed property dealer in Mohali dealing in residential flats across all major developers including Gillco, Wave, JLPL and Bestech. Trusted by 2000+ satisfied clients.','specializations'=>'Gillco Projects,Wave Estate,JLPL Projects','operating_cities'=>'Mohali,Zirakpur,Kharar'],
            ['first_name'=>'Sanjay','last_name'=>'Chawla','company_name'=>'Chawla Property Agency','phone'=>'+91 98141 66600','email'=>'sanjay@chawlapropertyagency.com','bio'=>'Chawla Property Agency specializes in Aerocity and Airport Zone properties in Mohali. Expert in GMADA Aerocity plots, IT City office spaces and Airport Road apartments.','specializations'=>'GMADA Aerocity,IT City,Airport Zone Properties','operating_cities'=>'Mohali,Zirakpur'],
            ['first_name'=>'Nitin','last_name'=>'Bawa','company_name'=>'Bawa Estate Agents Mohali','phone'=>'+91 98142 55500','email'=>'nitin.bawa@bawaestateagents.com','bio'=>'Bawa Estate Agents is a well-established property firm in Mohali with 14+ years of experience. Expert in premium residential transactions in Sectors 66-80 and investment advisory.','specializations'=>'Premium Residential,Investment Advisory','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Punit','last_name'=>'Midha','company_name'=>'Midha Property Dealers Mohali','phone'=>'+91 98140 33300','email'=>'midhapropertydealers.mohali@gmail.com','bio'=>'Midha Property Dealers provides genuine property listings and honest advisory in Mohali. Specializing in affordable and mid-segment properties in Kharar and Sector 100-117.','specializations'=>'Kharar Properties,Affordable Homes,Mid-Segment','operating_cities'=>'Mohali,Kharar,Zirakpur'],
            ['first_name'=>'Manish','last_name'=>'Aggarwal','company_name'=>'Aggarwal Realtors Mohali','phone'=>'+91 98764 22200','email'=>'manish@aggarwalrealtors.in','bio'=>'Aggarwal Realtors is a trusted name in Mohali real estate with a client base of 1500+ happy customers. Expert in new bookings with leading builders and resale transactions.','specializations'=>'New Bookings,Resale,Builder Deals','operating_cities'=>'Mohali,Zirakpur,Chandigarh,Panchkula'],
            ['first_name'=>'Sunil','last_name'=>'Khanna','company_name'=>'Khanna Properties Mohali','phone'=>'+91 98140 11100','email'=>'sunil@khannapropertiesmohali.com','bio'=>'Khanna Properties is based in Sector 70, Mohali with 16+ years of experience. Specializing in luxury apartment sales and rentals in Mohali\'s premium sectors.','specializations'=>'Luxury Apartments,Premium Rentals,Commercial','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Rohit','last_name'=>'Makhija','company_name'=>'Makhija Real Estate Mohali','phone'=>'+91 98762 99900','email'=>'makhijarealestate.mohali@gmail.com','bio'=>'Makhija Real Estate offers complete property solutions in Mohali and Zirakpur. Expert in Wave Estate, Emaar Hills and IREO City projects with strong investor connections.','specializations'=>'Wave Estate,Emaar Hills,IREO City','operating_cities'=>'Mohali,Zirakpur'],
            ['first_name'=>'Avinash','last_name'=>'Sood','company_name'=>'Sood Estate Advisors','phone'=>'+91 98763 44400','email'=>'avinash.sood@soodesateadvisors.com','bio'=>'Sood Estate Advisors provides professional real estate services in Mohali. Trusted by NRI investors and local buyers for fair and transparent property transactions.','specializations'=>'NRI Investment,Premium Apartments,Plots','operating_cities'=>'Mohali,Chandigarh,Zirakpur'],
            ['first_name'=>'Gaurav','last_name'=>'Sachdeva','company_name'=>'Sachdeva Properties Mohali','phone'=>'+91 98141 99900','email'=>'gaurav@sachdevaproperties.com','bio'=>'Sachdeva Properties is an experienced real estate agency in Mohali Phase 3B. Expert in Phase-wise property transactions, IT park commercial spaces and residential apartments.','specializations'=>'Phase Properties,IT Park,Commercial','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Amit','last_name'=>'Wadhwa','company_name'=>'Wadhwa Property Services','phone'=>'+91 98143 88800','email'=>'amit.wadhwa@wadhwapropertyservices.com','bio'=>'Wadhwa Property Services is a dedicated real estate consultancy in Mohali. Providing comprehensive services from property search to registration with expert legal assistance.','specializations'=>'Residential,Commercial,Legal Assistance','operating_cities'=>'Mohali,Zirakpur,Panchkula'],
            ['first_name'=>'Deepak','last_name'=>'Oswal','company_name'=>'Oswal Properties Mohali','phone'=>'+91 98144 77700','email'=>'deepak.oswal@oswalpropertiesmohali.com','bio'=>'Oswal Properties provides end-to-end real estate services in Mohali with 11 years of experience. Known for personalized service, transparent dealings and strong market knowledge.','specializations'=>'Residential,Commercial,Industrial Plots','operating_cities'=>'Mohali,Kharar,Zirakpur'],
            ['first_name'=>'Vishal','last_name'=>'Mehra','company_name'=>'Mehra Estate Mohali','phone'=>'+91 98766 33300','email'=>'vishal@mehraestatemohali.com','bio'=>'Mehra Estate is located in Sector 70, Mohali offering premium property services. Expert in Tata Primanti, JLPL and Godrej properties with investor-focused advisory.','specializations'=>'Tata Primanti,JLPL,Godrej Projects','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Ankur','last_name'=>'Jain','company_name'=>'Jain Property Hub Mohali','phone'=>'+91 98141 11100','email'=>'ankur.jain@jainpropertyhub.com','bio'=>'Jain Property Hub provides comprehensive real estate services in Mohali. Specializing in affordable housing in Kharar and Sectors 100-117 with budget-friendly options for families.','specializations'=>'Affordable Housing,Kharar,Sectors 100-117','operating_cities'=>'Mohali,Kharar'],
            ['first_name'=>'Sushil','last_name'=>'Dhingra','company_name'=>'Dhingra Properties Mohali','phone'=>'+91 98145 66600','email'=>'dhingra.properties.mohali@gmail.com','bio'=>'Dhingra Properties has been a trusted name in Mohali real estate since 2001. Specializing in Phase 1, 2 and 3A residential properties and commercial spaces.','specializations'=>'Phase 1-3A Properties,Commercial,Residential','operating_cities'=>'Mohali,Chandigarh,Panchkula'],
            ['first_name'=>'Rajan','last_name'=>'Kohli','company_name'=>'Kohli Real Estate Mohali','phone'=>'+91 98142 33300','email'=>'rajan@kohlirealestate.in','bio'=>'Kohli Real Estate is a premium real estate agency in Mohali dealing in luxury residences, villas and high-end commercial spaces. 15+ years of serving Tricity\'s elite property buyers.','specializations'=>'Luxury Residences,Villas,High-End Commercial','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Bharat','last_name'=>'Bhardwaj','company_name'=>'Bhardwaj Properties Mohali','phone'=>'+91 98763 77700','email'=>'bharat.bhardwaj@bhardwajproperties.in','bio'=>'Bhardwaj Properties is a reliable real estate agency in Mohali. Expert in plot transactions, builder floors and residential apartment sales across Mohali sectors.','specializations'=>'Plots,Builder Floors,Residential Apartments','operating_cities'=>'Mohali,Zirakpur,Kharar'],
            ['first_name'=>'Tarun','last_name'=>'Katyal','company_name'=>'Katyal Property Consultants','phone'=>'+91 98140 22200','email'=>'tarun.katyal@katyalpropertyconsultants.com','bio'=>'Katyal Property Consultants is based in Mohali Phase 7. Expert in commercial SCOs, Industrial Area plots and business space transactions with strong corporate client network.','specializations'=>'Commercial SCOs,Industrial Plots,Business Spaces','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Pardeep','last_name'=>'Bhatt','company_name'=>'Bhatt Real Estate Mohali','phone'=>'+91 98760 55000','email'=>'pardeep@bhattrealestatemohali.com','bio'=>'Bhatt Real Estate provides honest property dealing in Mohali since 2009. Helping buyers find the right properties in Mohali\'s booming real estate market at fair prices.','specializations'=>'Residential,Investment Properties,Resale','operating_cities'=>'Mohali,Zirakpur,Kharar'],
            ['first_name'=>'Arun','last_name'=>'Trehan','company_name'=>'Trehan Estate Services','phone'=>'+91 98141 44400','email'=>'arun.trehan@trehanestateservices.com','bio'=>'Trehan Estate Services provides comprehensive real estate advisory in Mohali. Specializing in GMADA sector residential plots and approved colony transactions.','specializations'=>'GMADA Plots,Approved Colonies,Residential','operating_cities'=>'Mohali,Chandigarh,Zirakpur'],
            ['first_name'=>'Rakesh','last_name'=>'Goel','company_name'=>'Goel Properties Mohali','phone'=>'+91 98763 22200','email'=>'rakesh.goel@goelproperties.in','bio'=>'Goel Properties is a veteran real estate agency in Mohali with 22+ years of experience. Known for deep market knowledge, investor-grade advisory and transparent dealings.','specializations'=>'Investment Advisory,Premium Apartments,Commercial','operating_cities'=>'Mohali,Chandigarh'],

            // ── CHANDIGARH DEALERS (40) ────────────────────────────────
            ['first_name'=>'Vivek','last_name'=>'Malhotra','company_name'=>'Malhotra Properties Chandigarh','phone'=>'+91 98158 55500','email'=>'vivek@malhotrapropertieschd.com','bio'=>'Malhotra Properties is one of Chandigarh\'s most trusted property agencies with 25+ years of experience. Specializing in premium sector properties, builder floors and commercial establishments.','specializations'=>'Sector Properties,Builder Floors,Commercial','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Rajiv','last_name'=>'Mehta','company_name'=>'Mehta Estate Agents','phone'=>'+91 98154 11100','email'=>'rajiv.mehta@mehtaestateagents.com','bio'=>'Mehta Estate Agents is a heritage real estate firm in Chandigarh established in 1985. Serving generations of Chandigarh families with expert property guidance and transparent dealings.','specializations'=>'Chandigarh Sectors,Builder Floors,Premium Residential','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Ashok','last_name'=>'Trehan','company_name'=>'Trehan Properties Chandigarh','phone'=>'+91 98156 66600','email'=>'ashok@trehanpropertieschd.in','bio'=>'Trehan Properties is a trusted real estate agency in Chandigarh Sector 35. Expert in Chandigarh sector-wise property transactions, ground floor and independent houses.','specializations'=>'Independent Houses,Ground Floor,Chandigarh Sectors','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Kamal','last_name'=>'Grover','company_name'=>'Grover & Grover Properties','phone'=>'+91 98156 33300','email'=>'kamal@groverandgrover.com','bio'=>'Grover & Grover Properties is a premium real estate consultancy in Chandigarh. Specializing in high-value residential and commercial transactions in Chandigarh\'s prime sectors.','specializations'=>'Premium Residential,Commercial,High-Value Properties','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Suresh','last_name'=>'Chandra','company_name'=>'Chandra Property Solutions','phone'=>'+91 98155 44400','email'=>'suresh.chandra@chandrapropertysolutions.com','bio'=>'Chandra Property Solutions provides comprehensive real estate services in Chandigarh. Expert in Sector 8-35 properties, builder floors and rental assistance.','specializations'=>'Sector 8-35 Properties,Builder Floors,Rental','operating_cities'=>'Chandigarh,Panchkula'],
            ['first_name'=>'Pankaj','last_name'=>'Chopra','company_name'=>'Chopra Real Estate Chandigarh','phone'=>'+91 98155 77700','email'=>'pankaj.chopra@chopraestates.com','bio'=>'Chopra Real Estate is a professional property firm in Chandigarh. Dealing in residential properties, commercial spaces and new project launches across Tricity since 2004.','specializations'=>'Residential,Commercial,New Launches','operating_cities'=>'Chandigarh,Mohali,Panchkula,Zirakpur'],
            ['first_name'=>'Naresh','last_name'=>'Arora','company_name'=>'Arora Estate Chandigarh','phone'=>'+91 98155 00000','email'=>'naresh.arora@aroraestates.in','bio'=>'Arora Estate is located in Sector 22, Chandigarh providing professional real estate services to buyers, sellers and tenants. Strong track record with 30+ years of experience.','specializations'=>'Sector 22 Properties,Commercial,Residential','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Devender','last_name'=>'Walia','company_name'=>'Walia Properties Chandigarh','phone'=>'+91 98158 99900','email'=>'devender@waliapropertieschd.com','bio'=>'Walia Properties is a veteran agency in Chandigarh dealing in residential houses, builder floors and commercial properties. Strong network across Chandigarh\'s government sectors.','specializations'=>'Independent Houses,Builder Floors,Commercial','operating_cities'=>'Chandigarh,Mohali'],
            ['first_name'=>'Anil','last_name'=>'Khosla','company_name'=>'Khosla Properties Chandigarh','phone'=>'+91 98155 88800','email'=>'anil@khoslapropertieschd.com','bio'=>'Khosla Properties provides trusted real estate services in Chandigarh since 1992. Expert in Chandigarh sector house sales, plot transactions and commercial property dealings.','specializations'=>'Chandigarh Houses,Plots,Commercial','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Vinod','last_name'=>'Rana','company_name'=>'Rana Property Dealers','phone'=>'+91 98156 22200','email'=>'vinod.rana@ranapropertydealers.com','bio'=>'Rana Property Dealers is a reliable real estate agency in Chandigarh. Expert in affordable sector properties for first-time buyers and investors seeking value for money.','specializations'=>'Affordable Properties,First-Time Buyers,Investment','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Harish','last_name'=>'Vij','company_name'=>'Vij Real Estate Chandigarh','phone'=>'+91 98157 33300','email'=>'harish.vij@vijrealestatechd.com','bio'=>'Vij Real Estate is based in Sector 34, Chandigarh. Providing premium real estate services including property valuation, buyer advisory and investment consulting for 20+ years.','specializations'=>'Property Valuation,Investment Consulting,Residential','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Hari','last_name'=>'Prasad','company_name'=>'Prasad Property Services','phone'=>'+91 98155 11100','email'=>'hariprasad.propertyservices@gmail.com','bio'=>'Prasad Property Services offers comprehensive real estate solutions in Chandigarh. Specializing in Mani Majra and fringe area properties at budget-friendly prices.','specializations'=>'Mani Majra Properties,Fringe Areas,Budget Homes','operating_cities'=>'Chandigarh,Mohali'],
            ['first_name'=>'Dinesh','last_name'=>'Sharma','company_name'=>'D.S. Properties Chandigarh','phone'=>'+91 98156 77700','email'=>'dinesh.sharma@dspropertieschd.com','bio'=>'D.S. Properties has been operating in Chandigarh since 2000. Expert in builder floor transactions, residential house purchases and commercial space leasing across Chandigarh sectors.','specializations'=>'Builder Floors,Residential Houses,Commercial Leasing','operating_cities'=>'Chandigarh,Panchkula'],
            ['first_name'=>'Prem','last_name'=>'Saini','company_name'=>'Saini Property Group Chandigarh','phone'=>'+91 98155 66600','email'=>'prem.saini@sainipropertygroup.com','bio'=>'Saini Property Group is a premium real estate firm in Chandigarh. Specializing in high-end residential properties, VIP sector houses and luxury apartment transactions.','specializations'=>'High-End Residential,VIP Sector Houses,Luxury','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Raj','last_name'=>'Kumar','company_name'=>'RK Properties Chandigarh','phone'=>'+91 98155 55500','email'=>'raj.kumar@rkpropertieschd.in','bio'=>'RK Properties provides honest real estate services in Chandigarh. Expert in Sector 40-49 properties, Manimajra apartments and Mullanpur (New Chandigarh) developments.','specializations'=>'Sector 40-49,Manimajra,New Chandigarh','operating_cities'=>'Chandigarh,Mohali'],
            ['first_name'=>'Gopal','last_name'=>'Das','company_name'=>'Das Estate Agents Chandigarh','phone'=>'+91 98158 77700','email'=>'gopal.das@daestateagentschd.com','bio'=>'Das Estate Agents is a trusted real estate firm in Chandigarh Sector 44. Known for residential house purchases, plot sales and post-sales documentation assistance.','specializations'=>'Residential Houses,Plots,Documentation','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Balram','last_name'=>'Negi','company_name'=>'Negi Properties Chandigarh','phone'=>'+91 98158 33300','email'=>'balramnegi.properties@gmail.com','bio'=>'Negi Properties is a well-established property dealer in Chandigarh dealing in affordable residential properties. Expert in budget homes, SFS flats and HIG/MIG apartments.','specializations'=>'SFS Flats,HIG Flats,Affordable Homes','operating_cities'=>'Chandigarh,Panchkula'],
            ['first_name'=>'Sanjiv','last_name'=>'Bhagat','company_name'=>'Bhagat Estate Consultants','phone'=>'+91 98154 88800','email'=>'sanjiv.bhagat@bhagatestates.com','bio'=>'Bhagat Estate Consultants provides professional real estate advisory in Chandigarh. Specializing in premium builder floors, independent houses and investment-grade properties.','specializations'=>'Premium Builder Floors,Independent Houses,Investment','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Rajendra','last_name'=>'Verma','company_name'=>'Verma Properties Chandigarh','phone'=>'+91 98155 22200','email'=>'rajendra.verma@vermapropertieschd.in','bio'=>'Verma Properties is an established real estate agency in Chandigarh offering full-service property solutions including buying, selling, renting and property management.','specializations'=>'Full Service,Property Management,Residential','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Lalit','last_name'=>'Chopra','company_name'=>'Chopra Property Consultants Chandigarh','phone'=>'+91 98154 66600','email'=>'lalit.chopra@choprapropertychd.com','bio'=>'Chopra Property Consultants is based in Sector 26, Chandigarh. Expert in commercial property transactions, SCOs and showroom leasing in Chandigarh\'s commercial hubs.','specializations'=>'Commercial SCOs,Showrooms,Commercial Leasing','operating_cities'=>'Chandigarh,Mohali'],

            // ── PANCHKULA DEALERS (35) ─────────────────────────────────
            ['first_name'=>'Suresh','last_name'=>'Bhandari','company_name'=>'Bhandari Properties Panchkula','phone'=>'+91 98120 55500','email'=>'suresh.bhandari@bhandariproperties.in','bio'=>'Bhandari Properties is a leading real estate agency in Panchkula with 20+ years of experience. Expert in all Panchkula sectors, extension sectors and Kalka-Panchkula Highway properties.','specializations'=>'Panchkula Sectors,Extension Sectors,Residential','operating_cities'=>'Panchkula,Chandigarh,Mohali,Zirakpur'],
            ['first_name'=>'Rakesh','last_name'=>'Puri','company_name'=>'Puri Estates Panchkula','phone'=>'+91 98120 77700','email'=>'rakesh.puri@puriestatespkl.com','bio'=>'Puri Estates has been serving Panchkula\'s property buyers and sellers since 1999. Trusted for honest dealing in residential apartments, independent houses and commercial spaces.','specializations'=>'Residential Apartments,Independent Houses,Commercial','operating_cities'=>'Panchkula,Chandigarh,Zirakpur'],
            ['first_name'=>'Mahesh','last_name'=>'Choudhary','company_name'=>'Choudhary Real Estate Panchkula','phone'=>'+91 98120 44400','email'=>'choudhary.realestate.pkul@gmail.com','bio'=>'Choudhary Real Estate is a trusted name in Panchkula property market. Expert in Sector 1-25 properties, residential apartments and SCO transactions across Panchkula.','specializations'=>'Sector 1-25,Residential,SCO Transactions','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Naveen','last_name'=>'Bhardwaj','company_name'=>'Bhardwaj Property Agents Panchkula','phone'=>'+91 98121 33300','email'=>'naveen.bhardwaj@bhardwajpropertyagents.com','bio'=>'Bhardwaj Property Agents offers professional real estate services in Panchkula. Specializing in sector houses, builder floors and new apartment bookings in Panchkula Extension.','specializations'=>'Sector Houses,Builder Floors,New Bookings','operating_cities'=>'Panchkula,Chandigarh,Mohali'],
            ['first_name'=>'Vinay','last_name'=>'Sharma','company_name'=>'Sharma Properties Panchkula','phone'=>'+91 98120 11100','email'=>'vinay.sharma@sharmapropertiespkl.com','bio'=>'Sharma Properties is a reliable property dealer in Panchkula. Expert in Sector 10-20 premium apartments and investment properties with strong market knowledge and client network.','specializations'=>'Sector 10-20,Premium Apartments,Investment','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Deepak','last_name'=>'Arya','company_name'=>'Arya Properties Panchkula','phone'=>'+91 98121 66600','email'=>'deepak.arya@aryapropertiespkl.in','bio'=>'Arya Properties has been helping property buyers and investors in Panchkula since 2006. Expert in residential apartments, plots in approved colonies and commercial spaces.','specializations'=>'Residential,Plots,Commercial Spaces','operating_cities'=>'Panchkula,Chandigarh,Mohali'],
            ['first_name'=>'Ramesh','last_name'=>'Sahni','company_name'=>'Sahni Property Consultants','phone'=>'+91 98121 22200','email'=>'ramesh.sahni@sahnipropertyconsultants.com','bio'=>'Sahni Property Consultants is a professional real estate firm in Panchkula. Known for transparent dealings, post-sale support and comprehensive property advisory in Panchkula Extension.','specializations'=>'Extension Sectors,Residential,Commercial','operating_cities'=>'Panchkula,Zirakpur,Chandigarh'],
            ['first_name'=>'Harish','last_name'=>'Bansal','company_name'=>'Bansal Properties Panchkula','phone'=>'+91 98120 88800','email'=>'harish.bansal@bansalpropertiespkl.com','bio'=>'Bansal Properties is a trusted property dealer in Panchkula. Dealing in residential houses, apartments, commercial shops and plots across Panchkula sectors and extension areas.','specializations'=>'Residential Houses,Commercial Shops,Plots','operating_cities'=>'Panchkula,Chandigarh,Mohali'],
            ['first_name'=>'Sanjeev','last_name'=>'Kapoor','company_name'=>'Kapoor Realtors Panchkula','phone'=>'+91 98120 22200','email'=>'sanjeev.kapoor@kaporrealtorespkl.com','bio'=>'Kapoor Realtors provides premium real estate services in Panchkula. Expert in luxury apartments by TDI, Navraj and other developers. Known for NRI property management services.','specializations'=>'Luxury Apartments,TDI Projects,Navraj Projects,NRI Services','operating_cities'=>'Panchkula,Chandigarh,Mohali'],
            ['first_name'=>'Mohan','last_name'=>'Lal','company_name'=>'Lal Estates Panchkula','phone'=>'+91 98120 33300','email'=>'mohan.lal@lalestates.in','bio'=>'Lal Estates has been a part of Panchkula\'s real estate landscape since 1995. Offering genuine property services for residential and commercial transactions.','specializations'=>'Residential,Commercial,Plots','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Raminder','last_name'=>'Singh','company_name'=>'Singh Property Services Panchkula','phone'=>'+91 98121 11100','email'=>'raminder.singh@singhpropertyservicespkl.com','bio'=>'Singh Property Services is a trusted property dealer in Panchkula. Expert in Sector 12A and Sector 25 premium residential properties and commercial establishment.','specializations'=>'Sector 12A,Sector 25,Residential,Commercial','operating_cities'=>'Panchkula,Chandigarh,Zirakpur'],
            ['first_name'=>'Tilak','last_name'=>'Raj','company_name'=>'Raj Properties Panchkula','phone'=>'+91 98121 99900','email'=>'tilak.raj@rajpropertiespkl.com','bio'=>'Raj Properties is a reliable real estate agency in Panchkula offering comprehensive property services. Specializing in budget homes in Sectors 5-12 and Panchkula Extension.','specializations'=>'Budget Homes,Sectors 5-12,Extension Area','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Kulbhushan','last_name'=>'Mittal','company_name'=>'Mittal Property Consultants Panchkula','phone'=>'+91 98120 66600','email'=>'kulbhushan.mittal@mittalpkl.com','bio'=>'Mittal Property Consultants is a professional real estate agency in Panchkula. Expert in investment-grade properties, commercial SCOs and high-value residential transactions.','specializations'=>'Investment Properties,Commercial SCOs,High-Value Residential','operating_cities'=>'Panchkula,Chandigarh,Mohali'],
            ['first_name'=>'Vikrant','last_name'=>'Thakur','company_name'=>'Thakur Properties Panchkula','phone'=>'+91 98121 55500','email'=>'vikrant.thakur@thakurpropertiespkl.com','bio'=>'Thakur Properties is a trusted name in Panchkula for residential and commercial property transactions. Known for professional service and honest market advice.','specializations'=>'Residential,Commercial,Rental','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Amrit','last_name'=>'Lal','company_name'=>'AL Properties Panchkula','phone'=>'+91 98120 00000','email'=>'alproperties.pkul@gmail.com','bio'=>'AL Properties provides full-service real estate solutions in Panchkula. Trusted by families and investors for genuine listings and professional advisory in Panchkula\'s residential market.','specializations'=>'Full Service,Residential,Investment','operating_cities'=>'Panchkula,Zirakpur,Chandigarh'],

            // ── MORE ZIRAKPUR & ADDITIONAL DEALERS ─────────────────────
            ['first_name'=>'Harjinder','last_name'=>'Saini','company_name'=>'Saini Property Dealers Zirakpur','phone'=>'+91 98726 88800','email'=>'sainipropertydealers.zrk@gmail.com','bio'=>'Saini Property Dealers is a leading real estate firm in Zirakpur offering genuine services. Specializing in Motia Group and SBP Group projects with 500+ successful transactions.','specializations'=>'Motia Projects,SBP Projects,Residential','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Gulab','last_name'=>'Singh','company_name'=>'G.S. Real Estate Zirakpur','phone'=>'+91 98765 00100','email'=>'gs.realestate.zrk@gmail.com','bio'=>'G.S. Real Estate is a reliable property dealer in Zirakpur with expertise in the Peer Mushalla and Dhakoli corridors. Trusted for transparent property dealings.','specializations'=>'Peer Mushalla,Dhakoli Properties,Residential','operating_cities'=>'Zirakpur,Chandigarh'],
            ['first_name'=>'Rampal','last_name'=>'Kaur','company_name'=>'Kaur Property Consultants','phone'=>'+91 98726 11500','email'=>'rampalkaur.properties@gmail.com','bio'=>'Kaur Property Consultants provides reliable real estate services in Zirakpur. Expert in affordable 2 BHK apartments and budget housing for working-class families.','specializations'=>'Affordable 2 BHK,Budget Housing,Residential','operating_cities'=>'Zirakpur,Derabassi'],
            ['first_name'=>'Jaspal','last_name'=>'Sohi','company_name'=>'Sohi Estate Agents','phone'=>'+91 98763 88900','email'=>'jaspalsohi.estate@gmail.com','bio'=>'Sohi Estate Agents has deep market knowledge of Zirakpur, Derabassi and Baltana real estate. Helping families find affordable homes with honest and transparent guidance.','specializations'=>'Derabassi,Baltana,Affordable Homes','operating_cities'=>'Zirakpur,Derabassi,Panchkula'],
            ['first_name'=>'Sukhjinder','last_name'=>'Basra','company_name'=>'Basra Properties','phone'=>'+91 98726 22600','email'=>'sukhjinder.basra@basraproperties.com','bio'=>'Basra Properties is a fast-growing real estate agency in Zirakpur. Expert in newly launched projects, NRI services and property portfolio management.','specializations'=>'New Launches,NRI Services,Portfolio Management','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Gursharan','last_name'=>'Kang','company_name'=>'Kang Property Services','phone'=>'+91 98725 33700','email'=>'gursharan.kang@kangpropertyservices.com','bio'=>'Kang Property Services offers comprehensive real estate solutions in Zirakpur. Dealing in residential, commercial and industrial properties with 10+ years of expertise.','specializations'=>'Residential,Commercial,Industrial','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Sukhchain','last_name'=>'Sekhon','company_name'=>'Sekhon Properties','phone'=>'+91 98762 55800','email'=>'sukhchainsekhon.properties@gmail.com','bio'=>'Sekhon Properties is a trusted property firm in Zirakpur. Specializing in GBP, Maya Builders and Tricity Infratech projects with strong resale market connections.','specializations'=>'GBP Projects,Maya Builders,Resale','operating_cities'=>'Zirakpur,Panchkula'],
            ['first_name'=>'Parminder','last_name'=>'Hundal','company_name'=>'Hundal Real Estate','phone'=>'+91 98765 77900','email'=>'parminder.hundal@hundralrealestate.com','bio'=>'Hundal Real Estate is a growing real estate agency in Zirakpur. Focused on providing genuine market insights and helping buyers make informed property decisions.','specializations'=>'Market Insights,Residential,Investment','operating_cities'=>'Zirakpur,Mohali,Chandigarh'],
            ['first_name'=>'Davinder','last_name'=>'Oberoi','company_name'=>'Oberoi Property Services Zirakpur','phone'=>'+91 98725 11900','email'=>'davinder.oberoi@oberoipropertyservices.com','bio'=>'Oberoi Property Services operates in Zirakpur with deep expertise in resale markets and secondary transactions. Known for finding the best deals for both buyers and sellers.','specializations'=>'Resale Market,Secondary Transactions,Best Deals','operating_cities'=>'Zirakpur,Mohali'],
            ['first_name'=>'Hakam','last_name'=>'Singh','company_name'=>'Hakam Properties','phone'=>'+91 98765 44200','email'=>'hakam.properties.zrk@gmail.com','bio'=>'Hakam Properties offers straightforward real estate services in Zirakpur. Expert in plot transactions, farmhouse sales and residential apartments in Zirakpur\'s fringe areas.','specializations'=>'Plots,Farmhouses,Fringe Area Properties','operating_cities'=>'Zirakpur,Derabassi'],
            ['first_name'=>'Joginder','last_name'=>'Pal','company_name'=>'JP Estate Zirakpur','phone'=>'+91 98726 99100','email'=>'jp.estate.zirakpur@gmail.com','bio'=>'JP Estate is a local Zirakpur property dealer with expertise in mid-segment residential apartments. Known for honest dealings and strong support during the property registration process.','specializations'=>'Mid-Segment Apartments,Registration Support,Residential','operating_cities'=>'Zirakpur,Panchkula,Chandigarh'],
            ['first_name'=>'Kirpal','last_name'=>'Singh','company_name'=>'Kirpal Property Dealers','phone'=>'+91 98763 55200','email'=>'kirpal.propertydealers@gmail.com','bio'=>'Kirpal Property Dealers provides trusted real estate services in Zirakpur and surrounding areas. Expert in affordable housing for first-time buyers and growing families.','specializations'=>'Affordable Housing,First-Time Buyers,Residential','operating_cities'=>'Zirakpur,Panchkula'],
            ['first_name'=>'Gurbaksh','last_name'=>'Rangi','company_name'=>'Rangi Properties Zirakpur','phone'=>'+91 98725 88100','email'=>'gurbaksh.rangi@rangiproperties.in','bio'=>'Rangi Properties is a reliable real estate firm in Zirakpur. Helping clients buy, sell and rent properties with complete transparency and professional market insights.','specializations'=>'Buy,Sell,Rent,Investment Advisory','operating_cities'=>'Zirakpur,Mohali,Panchkula'],
            ['first_name'=>'Parkash','last_name'=>'Dhaliwal','company_name'=>'PD Estates Zirakpur','phone'=>'+91 98726 44200','email'=>'parkash.dhaliwal@pdestates.in','bio'=>'PD Estates is a growing real estate agency in Zirakpur. Focused on delivering value to customers through honest market data and professional transaction support.','specializations'=>'Residential,Commercial,Plot Transactions','operating_cities'=>'Zirakpur,Derabassi,Mohali'],

            // ── ADDITIONAL MOHALI DEALERS ──────────────────────────────
            ['first_name'=>'Kulbir','last_name'=>'Brar','company_name'=>'Brar Estate Agents Mohali','phone'=>'+91 98143 11100','email'=>'kulbir.brar@brarestateagents.com','bio'=>'Brar Estate Agents is a professional property firm in Mohali Phase 2. Expert in residential transactions in Sectors 68-76 and commercial SCO leasing.','specializations'=>'Sectors 68-76,Commercial SCOs,Residential','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Gurvinder','last_name'=>'Panesar','company_name'=>'Panesar Real Estate Mohali','phone'=>'+91 98144 55500','email'=>'panesar.realestate.mohali@gmail.com','bio'=>'Panesar Real Estate provides dedicated property services in Mohali. Expert in Kharar properties, affordable housing and first-time buyer advisory.','specializations'=>'Kharar Properties,Affordable Housing,First-Time Buyers','operating_cities'=>'Mohali,Kharar,Zirakpur'],
            ['first_name'=>'Jagjit','last_name'=>'Bhullar','company_name'=>'Bhullar Properties Mohali','phone'=>'+91 98145 22200','email'=>'bhullarproperties.mohali@gmail.com','bio'=>'Bhullar Properties is a trusted name in Mohali with 14 years of real estate expertise. Dealing in residential apartments, plots and commercial spaces across Mohali.','specializations'=>'Residential,Plots,Commercial','operating_cities'=>'Mohali,Chandigarh,Kharar'],
            ['first_name'=>'Satpal','last_name'=>'Dhaliwal','company_name'=>'Dhaliwal Properties Mohali','phone'=>'+91 98146 33300','email'=>'satpal.dhaliwal@dhaliwalpropertiesmohali.com','bio'=>'Dhaliwal Properties offers comprehensive real estate services in Mohali. Known for investor-focused services and deep knowledge of the Mohali property market.','specializations'=>'Investment,Residential,Commercial','operating_cities'=>'Mohali,Zirakpur,Chandigarh'],
            ['first_name'=>'Harpal','last_name'=>'Sran','company_name'=>'Sran Estate Mohali','phone'=>'+91 98144 88800','email'=>'harpal.sran@sranestate.in','bio'=>'Sran Estate is a professional property agency in Mohali. Expert in Sector 85-99 residential developments and GMADA land acquisitions.','specializations'=>'Sector 85-99,GMADA Properties,Residential','operating_cities'=>'Mohali,Chandigarh'],
            ['first_name'=>'Harbhajan','last_name'=>'Gill','company_name'=>'Gill Estate Agents Mohali','phone'=>'+91 98143 44400','email'=>'harbhajangill.estate@gmail.com','bio'=>'Gill Estate Agents is a reliable real estate firm in Mohali. Expert in Pearl City Township, Ansal developments and mid-segment apartments in Sectors 100-115.','specializations'=>'Pearl City,Ansal Projects,Mid-Segment','operating_cities'=>'Mohali,Kharar'],
            ['first_name'=>'Simarjit','last_name'=>'Singh','company_name'=>'Simarjit Properties Mohali','phone'=>'+91 98145 99900','email'=>'simarjitproperties.mohali@gmail.com','bio'=>'Simarjit Properties is a fast-growing real estate agency in Mohali. Providing honest market analysis and professional property transaction support to buyers and investors.','specializations'=>'Market Analysis,Investment,Residential','operating_cities'=>'Mohali,Zirakpur,Chandigarh'],
            ['first_name'=>'Gurjant','last_name'=>'Sohal','company_name'=>'Sohal Properties Mohali','phone'=>'+91 98146 66600','email'=>'gurjant.sohal@sohalpropertiesmohali.com','bio'=>'Sohal Properties has been serving the Mohali property market since 2007. Known for personalized service, honest pricing and comprehensive buyer support.','specializations'=>'Residential,Plots,Commercial','operating_cities'=>'Mohali,Chandigarh,Kharar'],

            // ── ADDITIONAL PANCHKULA DEALERS ──────────────────────────
            ['first_name'=>'Rajinder','last_name'=>'Kapoor','company_name'=>'Kapoor Property Services Panchkula','phone'=>'+91 98121 77700','email'=>'rajinder.kapoor@kapoorpropertyservicespkl.com','bio'=>'Kapoor Property Services is a well-established real estate firm in Panchkula. Expert in Sector 18-25 residential properties and Panchkula Extension developments.','specializations'=>'Sector 18-25,Extension Properties,Residential','operating_cities'=>'Panchkula,Chandigarh,Zirakpur'],
            ['first_name'=>'Paramvir','last_name'=>'Rana','company_name'=>'Rana Properties Panchkula','phone'=>'+91 98121 44400','email'=>'paramvir.rana@ranapropertiespkl.in','bio'=>'Rana Properties is a trusted property dealer in Panchkula. Expert in Navraj and TDI projects, investment-grade apartments and sector house purchases.','specializations'=>'Navraj Projects,TDI Projects,Investment','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Ashwani','last_name'=>'Garg','company_name'=>'Garg Estate Panchkula','phone'=>'+91 98122 11100','email'=>'ashwani.garg@gargestatepkl.com','bio'=>'Garg Estate is a professional real estate agency in Panchkula. Specializing in commercial SCO transactions, Sector 1-10 house sales and investment advisory.','specializations'=>'Commercial SCOs,Sector 1-10,Investment','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Kamlesh','last_name'=>'Ahuja','company_name'=>'Ahuja Properties Panchkula','phone'=>'+91 98121 88800','email'=>'kamlesh.ahuja@ahujapropertiespkl.com','bio'=>'Ahuja Properties provides honest property services in Panchkula. Expert in residential apartment rentals, house purchases and commercial space leasing in prime Panchkula locations.','specializations'=>'Rentals,Residential,Commercial Leasing','operating_cities'=>'Panchkula,Chandigarh,Mohali'],
            ['first_name'=>'Surinder','last_name'=>'Nagi','company_name'=>'Nagi Estate Consultants Panchkula','phone'=>'+91 98122 33300','email'=>'surinder.nagi@nagiestatepkl.com','bio'=>'Nagi Estate Consultants is a dedicated real estate agency in Panchkula. Providing complete property solutions including buyer representation and investment advisory.','specializations'=>'Buyer Representation,Investment,Residential','operating_cities'=>'Panchkula,Chandigarh,Zirakpur'],
            ['first_name'=>'Satish','last_name'=>'Sharma','company_name'=>'Satish Sharma Properties Panchkula','phone'=>'+91 98122 55500','email'=>'satish.sharma.properties@gmail.com','bio'=>'Satish Sharma Properties is a reliable name in Panchkula real estate. Known for market expertise, genuine listings and professional service across all price segments.','specializations'=>'Residential,Plots,Commercial','operating_cities'=>'Panchkula,Chandigarh'],
            ['first_name'=>'Deepinder','last_name'=>'Rathore','company_name'=>'Rathore Real Estate Panchkula','phone'=>'+91 98121 00000','email'=>'deepinder.rathore@rathorepkl.in','bio'=>'Rathore Real Estate is a growing real estate agency in Panchkula. Expert in Sector 20-25 premium residential properties and luxury apartment transactions.','specializations'=>'Sector 20-25,Premium Residential,Luxury','operating_cities'=>'Panchkula,Chandigarh,Mohali'],

            // ── MORE CHANDIGARH & MIXED DEALERS ────────────────────────
            ['first_name'=>'Rajesh','last_name'=>'Dhawan','company_name'=>'Dhawan Properties Chandigarh','phone'=>'+91 98154 00000','email'=>'rajesh.dhawan@dhawanpropertieschd.com','bio'=>'Dhawan Properties is an experienced real estate agency in Chandigarh. Expert in Sector 15-25 residential transactions and commercial property dealings.','specializations'=>'Sector 15-25,Residential,Commercial','operating_cities'=>'Chandigarh,Panchkula'],
            ['first_name'=>'Sanjay','last_name'=>'Khurmi','company_name'=>'Khurmi Estate Services','phone'=>'+91 98155 33300','email'=>'sanjay.khurmi@khurmiestateservices.com','bio'=>'Khurmi Estate Services offers professional real estate services in Chandigarh and Tricity. Known for transparent dealings, honest advisory and strong post-sale support.','specializations'=>'Residential,Commercial,Post-Sale Support','operating_cities'=>'Chandigarh,Mohali,Panchkula,Zirakpur'],
            ['first_name'=>'Brij','last_name'=>'Bhushan','company_name'=>'BB Properties Chandigarh','phone'=>'+91 98154 22200','email'=>'brijbhushan.properties@gmail.com','bio'=>'BB Properties is an established property firm in Chandigarh. Expert in residential house sales in Sector 36-45 and builder floor transactions for NRI clients.','specializations'=>'Sector 36-45,Builder Floors,NRI Services','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Navin','last_name'=>'Luthra','company_name'=>'Luthra Property Consultants','phone'=>'+91 98154 44400','email'=>'navin.luthra@luthrapropertyconsultants.com','bio'=>'Luthra Property Consultants is a professional real estate agency in Chandigarh. Providing comprehensive property services including market valuation, investment advisory and transaction support.','specializations'=>'Valuation,Investment Advisory,Transaction Support','operating_cities'=>'Chandigarh,Mohali,Panchkula,Zirakpur'],
            ['first_name'=>'Sham','last_name'=>'Bhatia','company_name'=>'Bhatia Properties Chandigarh','phone'=>'+91 98156 55500','email'=>'sham.bhatia@bhatiapropertieschd.in','bio'=>'Bhatia Properties has been operating in Chandigarh since 1990. Trusted by generations of Chandigarh families for honest property guidance and professional transaction support.','specializations'=>'Chandigarh Houses,Builder Floors,Investment','operating_cities'=>'Chandigarh,Panchkula,Mohali'],
            ['first_name'=>'Mohit','last_name'=>'Gupta','company_name'=>'Gupta Properties Tricity','phone'=>'+91 98765 22800','email'=>'mohit.gupta@guptatricityproperties.com','bio'=>'Gupta Properties serves the entire Tricity region with a strong network across Chandigarh, Mohali, Panchkula and Zirakpur. Expert in cross-city property transactions and investment advisory.','specializations'=>'Pan-Tricity Services,Investment,Cross-City Transactions','operating_cities'=>'Chandigarh,Mohali,Panchkula,Zirakpur'],
            ['first_name'=>'Sandeep','last_name'=>'Nagpal','company_name'=>'Nagpal Real Estate Chandigarh','phone'=>'+91 98154 77700','email'=>'sandeep.nagpal@nagpalrealestate.in','bio'=>'Nagpal Real Estate is a trusted property agency in Chandigarh with 15+ years of experience. Expert in premium sector residential transactions and luxury apartment dealings.','specializations'=>'Premium Residential,Luxury Apartments,Commercial','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
            ['first_name'=>'Rahul','last_name'=>'Dewan','company_name'=>'Dewan Properties Chandigarh','phone'=>'+91 98155 99900','email'=>'rahul.dewan@dewanpropertieschd.com','bio'=>'Dewan Properties provides modern real estate services in Chandigarh. Using digital marketing and data-driven approaches to help buyers find their ideal properties faster.','specializations'=>'Digital Listings,Modern Approach,Residential,Commercial','operating_cities'=>'Chandigarh,Mohali,Panchkula'],
        ];

        $inserted = 0;
        $skipped  = 0;

        foreach ($dealers as $dealer) {
            if (DB::table('property_dealers')->where('email', $dealer['email'])->exists()) {
                $this->command->warn("  [skip] {$dealer['first_name']} {$dealer['last_name']} — email already exists");
                $skipped++;
                continue;
            }

            $baseName = trim($dealer['first_name'] . ' ' . $dealer['last_name']);
            $slug = Str::slug($baseName);
            $original = $slug; $cnt = 1;
            while (DB::table('property_dealers')->where('slug', $slug)->exists()) {
                $slug = $original . '-' . $cnt++;
            }

            DB::table('property_dealers')->insert([
                'slug'             => $slug,
                'first_name'       => $dealer['first_name'],
                'last_name'        => $dealer['last_name'],
                'company_name'     => $dealer['company_name'],
                'phone'            => $dealer['phone'],
                'email'            => $dealer['email'],
                'password'         => Hash::make('Dealer@2024'),
                'bio'              => $dealer['bio'],
                'specializations'  => $dealer['specializations'],
                'operating_cities' => $dealer['operating_cities'],
                'status'           => 'active',
                'created_at'       => now(),
                'updated_at'       => now(),
            ]);
            $this->command->line("  ✓ Dealer: {$dealer['first_name']} {$dealer['last_name']} — {$dealer['company_name']}");
            $inserted++;
        }

        $this->command->info("  → Inserted: {$inserted} dealers, Skipped: {$skipped}");
    }
}
