<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TricityRealDataSeederBatch2 extends Seeder
{
    public function run(): void
    {
        $this->command->info('Seeding Tricity real estate data — Batch 2...');
        $this->seedBuilders();
        $this->command->info('✅ Batch 2 done!');
    }

    private function seedBuilders(): void
    {
        $this->command->info('  → Seeding builders (batch 2)...');

        $builders = [

            /* ── 1. NK Sharma Group ─────────────────────────────────── */
            [
                'name'                     => 'NK Sharma Group',
                'company_name'             => 'NK Sharma Group of Companies',
                'email'                    => 'info@nksharmagroup.com',
                'phone'                    => '+91 98156 00099',
                'website'                  => 'https://www.nksharmagroup.com',
                'city'                     => 'Zirakpur',
                'established_year'         => '2000',
                'rera_registration'        => 'PBRERA-SAS79-PR0163',
                'cities_operating'         => 'Zirakpur,Mohali,Panchkula',
                'rating'                   => 4.1,
                'is_verified'              => true,
                'total_delivered_projects' => 7,
                'description'              => 'NK Sharma Group has established itself as one of Punjab\'s premier real estate development companies since 2000. With 7+ prestigious projects ranging from 7 to 26 acres, they are synonymous with quality craftsmanship and timely delivery. Their Savitry Greens projects have transformed Zirakpur\'s residential landscape with modern, affordable homes.',
                'projects'                 => [
                    [
                        'title'            => 'NK Savitry Greens 2',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Gazipur Road, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 956,
                        'available_units'  => 70,
                        'price_from'       => 3000000,
                        'price_to'         => 8000000,
                        'possession_date'  => '2022-06-30',
                        'rera_id'          => 'PBRERA-SAS79-PR0163',
                        'total_towers'     => 12,
                        'floors_per_tower' => '11',
                        'latitude'         => 30.6500,
                        'longitude'        => 76.8230,
                        'amenities'        => 'Clubhouse,Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security,Landscaped Gardens,Car Parking,CCTV Surveillance',
                        'nearby_schools'   => 'Satluj Public School (2 km), Shivalik International School (3 km)',
                        'nearby_hospitals' => 'Healing Hospital (3 km), Mukat Hospital (5 km)',
                        'metro_distance'   => '7 km from Chandigarh',
                        'is_featured'      => true,
                        'description'      => 'NK Savitry Greens 2 is one of Zirakpur\'s most sought-after residential projects spanning 26 acres on Gazipur Road. Offering 2, 3 and 3.5 BHK apartments across 12 towers with excellent amenities and lush green surroundings. RERA approved, ready to move.',
                    ],
                    [
                        'title'            => 'NK Savitry Greens 1',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'VIP Road, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 600,
                        'available_units'  => 30,
                        'price_from'       => 2800000,
                        'price_to'         => 5500000,
                        'possession_date'  => '2019-12-31',
                        'rera_id'          => 'PBRERA-SAS79-PR0100',
                        'total_towers'     => 8,
                        'floors_per_tower' => '10',
                        'latitude'         => 30.6460,
                        'longitude'        => 76.8200,
                        'amenities'        => '24x7 Security,Power Backup,Gymnasium,Kids Play Area,Landscaped Gardens,Car Parking,Jogging Track,Club House',
                        'nearby_schools'   => 'Shivalik Public School (1.5 km)',
                        'nearby_hospitals' => 'Civil Hospital Zirakpur (3 km)',
                        'metro_distance'   => '7 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'NK Savitry Greens Phase 1 is a well-established residential colony on VIP Road, Zirakpur. Offering affordable 2 & 3 BHK apartments with essential amenities in a green, peaceful environment. Fully ready to move.',
                    ],
                ],
            ],

            /* ── 2. Mona Townships ──────────────────────────────────── */
            [
                'name'                     => 'Mona Townships',
                'company_name'             => 'Mona Townships Pvt. Ltd.',
                'email'                    => 'info@monatownship.com',
                'phone'                    => '+91 98760 01122',
                'website'                  => 'https://www.monatownship.com',
                'city'                     => 'Zirakpur',
                'established_year'         => '1990',
                'rera_registration'        => 'PBRERA-SAS79-PR0280',
                'cities_operating'         => 'Zirakpur,Mohali,Panchkula',
                'rating'                   => 3.9,
                'is_verified'              => true,
                'total_delivered_projects' => 5,
                'description'              => 'Mona Townships Pvt. Ltd. (MTPL) is a leading real estate developer with over three decades of experience in North India. Renowned for high-end residential developments that personify class and refinement, their Mona Greens projects set the benchmark for luxury living in Zirakpur.',
                'projects'                 => [
                    [
                        'title'            => 'Mona Greens',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'VIP Road, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 283,
                        'available_units'  => 25,
                        'price_from'       => 3552000,
                        'price_to'         => 7334000,
                        'possession_date'  => '2020-03-31',
                        'rera_id'          => 'PBRERA-SAS79-PR0280',
                        'total_towers'     => 4,
                        'floors_per_tower' => '14',
                        'latitude'         => 30.6470,
                        'longitude'        => 76.8175,
                        'amenities'        => 'Kids Play Area,Power Backup,Treated Water Supply,24x7 Security,Landscaped Garden,Basement Parking,Indoor Games,Intercom,CCTV',
                        'nearby_schools'   => 'St. Mary\'s School (2 km), Innocent Hearts (3 km)',
                        'nearby_hospitals' => 'Mukat Hospital (4 km)',
                        'metro_distance'   => '6 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Mona Greens on VIP Road, Zirakpur offers luxury 2, 3 and 4 BHK apartments across 4 high-rise towers on 5 acres. Premium living with refined architecture, power backup, security and landscaped surroundings. Ready to move.',
                    ],
                    [
                        'title'            => 'Mona Greens 2',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Gazipur Road, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 350,
                        'available_units'  => 40,
                        'price_from'       => 4549000,
                        'price_to'         => 9135000,
                        'possession_date'  => '2023-03-31',
                        'rera_id'          => 'PBRERA-SAS79-PR0766',
                        'total_towers'     => 6,
                        'floors_per_tower' => '14',
                        'latitude'         => 30.6505,
                        'longitude'        => 76.8235,
                        'amenities'        => 'Party Lawn,Yoga & Meditation Area,Indoor Games,24x7 Security,Power Backup,Earthquake Resistant Structure,Landscaped Gardens,Car Parking,CCTV',
                        'nearby_schools'   => 'Greenfield International School (1 km)',
                        'nearby_hospitals' => 'Healing Hospital (3.5 km)',
                        'metro_distance'   => '7 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Mona Greens 2 at Gazipur, Zirakpur offers spacious 3 & 4 BHK luxury apartments with premium finishes. Earthquake-resistant RCC structure with modern amenities and peaceful surroundings. RERA registered.',
                    ],
                ],
            ],

            /* ── 3. Wave Infratech ──────────────────────────────────── */
            [
                'name'                     => 'Wave Infratech',
                'company_name'             => 'Wave Infratech Pvt. Ltd.',
                'email'                    => 'info@waveestate.in',
                'phone'                    => '+91 172 463 0000',
                'website'                  => 'https://www.waveestate.in',
                'city'                     => 'Mohali',
                'established_year'         => '2000',
                'rera_registration'        => 'PBRERA-SAS81-PR0148',
                'cities_operating'         => 'Mohali,Chandigarh,Noida,Amritsar',
                'rating'                   => 3.8,
                'is_verified'              => true,
                'total_delivered_projects' => 12,
                'description'              => 'Wave Infratech is the real estate arm of the Wave Group, creating IGBC pre-certified green townships. Their landmark Wave Estate in Sector 85, Mohali spans 235 acres — a fully gated community designed by renowned international consultant ATKINS UK with premium villas, plots, apartments, commercial spaces and schools.',
                'projects'                 => [
                    [
                        'title'            => 'Wave Estate',
                        'project_type'     => 'Township',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 85-99, SAS Nagar, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 1200,
                        'available_units'  => 80,
                        'price_from'       => 15900000,
                        'price_to'         => 61100000,
                        'possession_date'  => '2021-12-31',
                        'rera_id'          => 'PBRERA-SAS81-PR0148',
                        'total_towers'     => 9,
                        'floors_per_tower' => '14',
                        'latitude'         => 30.7180,
                        'longitude'        => 76.7090,
                        'amenities'        => 'IGBC Green Certified,International Club,5-Star Facilities,Swimming Pool,Spa,Gymnasium,Tennis Court,Squash Court,Badminton Court,Cricket Net,Basketball Court,Jogging Track,Kids Play Area,24x7 Security,Power Backup',
                        'nearby_schools'   => 'Wave International School (on campus)',
                        'nearby_hospitals' => 'Max Super Speciality Hospital (5 km)',
                        'metro_distance'   => '10 km from Chandigarh',
                        'is_featured'      => true,
                        'description'      => 'Wave Estate is a 235-acre IGBC pre-certified silver-rated green township in Sector 85, Mohali. Designed by international consultant ATKINS UK, it offers ultra-luxury 3, 4 & 5 BHK apartments, villas, independent floors, plots, SCOs and commercial areas in a fully gated community.',
                    ],
                    [
                        'title'            => 'Wave Boulevard Floors',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Wave Estate, Sector 85, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 300,
                        'available_units'  => 35,
                        'price_from'       => 9000000,
                        'price_to'         => 16000000,
                        'possession_date'  => '2022-06-30',
                        'rera_id'          => 'PBRERA-SAS81-PR1009',
                        'total_towers'     => null,
                        'floors_per_tower' => '4',
                        'latitude'         => 30.7182,
                        'longitude'        => 76.7092,
                        'amenities'        => 'Modular Kitchen,Premium Fittings,Power Backup,24x7 Security,Landscaped Garden,Car Parking,CCTV',
                        'nearby_schools'   => 'Wave International School (1 km)',
                        'nearby_hospitals' => 'Max Hospital Mohali (5 km)',
                        'metro_distance'   => '10 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Wave Boulevard offers luxury independent floors within the prestigious Wave Estate township. Premium 3 BHK floors with modular kitchens, premium fittings and all township amenities accessible to residents.',
                    ],
                ],
            ],

            /* ── 4. Emaar India ─────────────────────────────────────── */
            [
                'name'                     => 'Emaar India',
                'company_name'             => 'Emaar India Pvt. Ltd.',
                'email'                    => 'customercare@emaarindia.com',
                'phone'                    => '+91 124 442 1111',
                'website'                  => 'https://in.emaar.com',
                'city'                     => 'Mohali',
                'established_year'         => '2005',
                'rera_registration'        => 'PBRERA-SAS81-PR0119',
                'cities_operating'         => 'Mohali,Gurugram,Lucknow,Indore,Chennai',
                'rating'                   => 4.2,
                'is_verified'              => true,
                'total_delivered_projects' => 18,
                'description'              => 'Emaar India is a subsidiary of Emaar Properties, the globally acclaimed Dubai-based real estate developer. Bringing international-standard real estate to India since 2005, their Mohali Hills township in Sector 105 spans 300+ acres with premium apartments, villas and plots — a truly world-class address in the Tricity.',
                'projects'                 => [
                    [
                        'title'            => 'Emaar The Views — Mohali Hills',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 105, Kharar-Banur Road, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 800,
                        'available_units'  => 60,
                        'price_from'       => 5890000,
                        'price_to'         => 12400000,
                        'possession_date'  => '2021-09-30',
                        'rera_id'          => 'PBRERA-SAS81-PR0119',
                        'total_towers'     => 14,
                        'floors_per_tower' => '13',
                        'latitude'         => 30.7820,
                        'longitude'        => 76.6980,
                        'amenities'        => 'International Club House,Swimming Pool,Gymnasium,Meditation Hall,Amphitheatre,Kids Play Area,Jogging Track,Landscaped Gardens,24x7 Security,Power Backup,Indoor Games,Rain Water Harvesting,Bank/ATM',
                        'nearby_schools'   => 'Delhi Public School (3 km), Strawberry Fields (4 km)',
                        'nearby_hospitals' => 'Fortis Hospital (8 km)',
                        'metro_distance'   => '15 km from Chandigarh',
                        'is_featured'      => true,
                        'description'      => 'Emaar The Views at Mohali Hills is an internationally designed premium residential project in Sector 105. Offering 2, 3 & 4 BHK apartments and penthouses across 19.5 acres with world-class amenities. G+8 and G+13 towers with stunning views.',
                    ],
                    [
                        'title'            => 'Emaar Mohali Hills — Residential Plots',
                        'project_type'     => 'Plotted',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 105-106, Kharar-Banur Road, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 1500,
                        'available_units'  => 120,
                        'price_from'       => 15800000,
                        'price_to'         => 62500000,
                        'possession_date'  => '2019-01-01',
                        'rera_id'          => 'PBRERA-SAS80-PR0060',
                        'total_towers'     => null,
                        'floors_per_tower' => null,
                        'latitude'         => 30.7830,
                        'longitude'        => 76.6975,
                        'amenities'        => 'Wide Tree-Lined Roads,Underground Utilities,24x7 Security,Lush Green Parks,Community Centre,Sports Facilities',
                        'nearby_schools'   => 'Emaar International School (upcoming)',
                        'nearby_hospitals' => 'Fortis Hospital (8 km)',
                        'metro_distance'   => '15 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Emaar Mohali Hills Residential Plots at Sector 105 offer premium freehold plots in sizes from 1710 to 6750 sqft within a 300-acre internationally planned township. Ideal for investors and self-construction buyers seeking a prestigious address.',
                    ],
                ],
            ],

            /* ── 5. Ansal API ───────────────────────────────────────── */
            [
                'name'                     => 'Ansal API',
                'company_name'             => 'Ansal Properties & Infrastructure Ltd.',
                'email'                    => 'info@ansalapi.com',
                'phone'                    => '+91 11 2335 3550',
                'website'                  => 'https://www.ansalapi.com',
                'city'                     => 'Mohali',
                'established_year'         => '1967',
                'rera_registration'        => 'PBRERA-SAS80-PR0150',
                'cities_operating'         => 'Mohali,Delhi,Lucknow,Jaipur,Agra',
                'rating'                   => 3.6,
                'is_verified'              => true,
                'total_delivered_projects' => 50,
                'description'              => 'Ansal API (Ansal Properties & Infrastructure) is one of India\'s oldest real estate developers, established in 1967. With 50+ years of expertise across 25+ cities, they bring quality integrated townships and group housing to Mohali\'s Sector 115 at highly competitive prices.',
                'projects'                 => [
                    [
                        'title'            => 'Ansal Orchard County',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 115, Kharar-Banur Road, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 800,
                        'available_units'  => 55,
                        'price_from'       => 3124000,
                        'price_to'         => 5000000,
                        'possession_date'  => '2018-12-31',
                        'rera_id'          => 'PBRERA-SAS80-PR0150',
                        'total_towers'     => 20,
                        'floors_per_tower' => '10',
                        'latitude'         => 30.7530,
                        'longitude'        => 76.7110,
                        'amenities'        => 'Clubhouse,Swimming Pool,Kids Play Area,Jogging Track,24x7 Security,Power Backup,Landscaped Garden,Car Parking',
                        'nearby_schools'   => 'Ansal University (5 km), DAV School (3 km)',
                        'nearby_hospitals' => 'Fortis Hospital (10 km)',
                        'metro_distance'   => '14 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Ansal Orchard County in Sector 115, Mohali spans 22.28 acres offering affordable 2 & 3 BHK apartments. Ideal for first-time home buyers and investors. Good connectivity to Chandigarh via the Kharar-Banur Road. Ready to move.',
                    ],
                    [
                        'title'            => 'Ansal Palm Grove',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 115, Kharar-Banur Road, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 400,
                        'available_units'  => 30,
                        'price_from'       => 4500000,
                        'price_to'         => 6500000,
                        'possession_date'  => '2019-06-30',
                        'rera_id'          => 'PBRERA-SAS80-PR0155',
                        'total_towers'     => 10,
                        'floors_per_tower' => '12',
                        'latitude'         => 30.7525,
                        'longitude'        => 76.7115,
                        'amenities'        => 'Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,24x7 Security,Power Backup,Party Lawn,Indoor Games',
                        'nearby_schools'   => 'Shivalik Public School (2 km)',
                        'nearby_hospitals' => 'Fortis Hospital (10 km)',
                        'metro_distance'   => '14 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Ansal Palm Grove is a well-planned residential project in Sector 115, Mohali offering 3 BHK apartments at competitive prices. A peaceful gated community with modern amenities and excellent road connectivity.',
                    ],
                ],
            ],

            /* ── 6. JLPL Group ──────────────────────────────────────── */
            [
                'name'                     => 'JLPL Group',
                'company_name'             => 'JLPL Group (Janta Land Promoters Ltd.)',
                'email'                    => 'info@jantahousing.com',
                'phone'                    => '+91 97793 93200',
                'website'                  => 'https://www.jantahousing.com',
                'city'                     => 'Mohali',
                'established_year'         => '1995',
                'rera_registration'        => 'PBRERA-SAS81-PM0003',
                'cities_operating'         => 'Mohali,Chandigarh,Zirakpur',
                'rating'                   => 4.0,
                'is_verified'              => true,
                'total_delivered_projects' => 15,
                'description'              => 'JLPL Group (Janta Land Promoters Ltd.) has been building premium homes in Mohali since 1995. Their 398-acre mega-township across Sectors 90, 91 and 82 is one of the largest in Punjab. Known for world-class luxury projects like Falcon View — a 5-star club house residential project that sets the standard for luxury living in Mohali.',
                'projects'                 => [
                    [
                        'title'            => 'JLPL Falcon View',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 66A, SAS Nagar, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 400,
                        'available_units'  => 45,
                        'price_from'       => 24800000,
                        'price_to'         => 55700000,
                        'possession_date'  => '2022-09-30',
                        'rera_id'          => 'PBRERA-SAS81-PM0003',
                        'total_towers'     => 10,
                        'floors_per_tower' => '15',
                        'latitude'         => 30.7040,
                        'longitude'        => 76.7440,
                        'amenities'        => '5-Star Clubhouse,Restaurant,Banquet Halls,Swimming Pool,Gymnasium,Yoga Hall,Amphitheatre,Indoor Games,Outdoor Games,Tennis Court,Squash Court,Jogging Track,24x7 Security,Power Backup,EV Charging',
                        'nearby_schools'   => 'Strawberry Fields High School (2 km)',
                        'nearby_hospitals' => 'Fortis Hospital Mohali (4 km)',
                        'metro_distance'   => '5 km from Chandigarh',
                        'is_featured'      => true,
                        'description'      => 'JLPL Falcon View in Sector 66A, Mohali is a world-class ultra-luxury residential project spread over 16.94 acres. Offering premium 3, 4 & 5 BHK apartments (2480–5570 sqft) with a lavish 5-star clubhouse featuring a restaurant, banquet halls, swimming pool, gymnasium and state-of-the-art sports facilities.',
                    ],
                    [
                        'title'            => 'JLPL Galaxy Heights',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Sector 66A, SAS Nagar, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 240,
                        'available_units'  => 25,
                        'price_from'       => 5500000,
                        'price_to'         => 9000000,
                        'possession_date'  => '2020-12-31',
                        'rera_id'          => 'PBRERA-SAS81-PR0200',
                        'total_towers'     => 6,
                        'floors_per_tower' => '12',
                        'latitude'         => 30.7042,
                        'longitude'        => 76.7442,
                        'amenities'        => 'Swimming Pool,Clubhouse,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security,Landscaped Garden',
                        'nearby_schools'   => 'Strawberry Fields High School (2 km)',
                        'nearby_hospitals' => 'Fortis Hospital (4 km)',
                        'metro_distance'   => '5 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'JLPL Galaxy Heights in Sector 66A, Mohali offers well-designed 2 BHK apartments across 4.12 acres with modern amenities. An affordable entry point into the prestigious JLPL Sector 66A community.',
                    ],
                    [
                        'title'            => 'JLPL Sky Gardens',
                        'project_type'     => 'Residential',
                        'status'           => 'Under Construction',
                        'address'          => 'Sector 66A, SAS Nagar, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 360,
                        'available_units'  => 180,
                        'price_from'       => 7500000,
                        'price_to'         => 12000000,
                        'possession_date'  => '2026-03-31',
                        'rera_id'          => 'PBRERA-SAS81-PR0250',
                        'total_towers'     => 8,
                        'floors_per_tower' => '14',
                        'latitude'         => 30.7045,
                        'longitude'        => 76.7445,
                        'amenities'        => 'Rooftop Garden,Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security,High-Speed Elevators',
                        'nearby_schools'   => 'Strawberry Fields High School (2 km)',
                        'nearby_hospitals' => 'Fortis Hospital (4 km)',
                        'metro_distance'   => '5 km from Chandigarh',
                        'is_featured'      => true,
                        'description'      => 'JLPL Sky Gardens is a premium 2+1 BHK residential project in Sector 66A, Mohali. Featuring rooftop gardens and modern architecture, it offers contemporary living with the pedigree of the JLPL brand. Possession March 2026.',
                    ],
                ],
            ],

            /* ── 7. Paras Buildtech ─────────────────────────────────── */
            [
                'name'                     => 'Paras Buildtech',
                'company_name'             => 'Paras Buildtech Pvt. Ltd.',
                'email'                    => 'info@parasbuildtech.com',
                'phone'                    => '+91 124 465 9000',
                'website'                  => 'https://www.parasbuildtech.com',
                'city'                     => 'Mohali',
                'established_year'         => '2000',
                'rera_registration'        => 'PBRERA-SAS80-PR0300',
                'cities_operating'         => 'Mohali,Kharar,Gurugram,Noida',
                'rating'                   => 3.9,
                'is_verified'              => true,
                'total_delivered_projects' => 18,
                'description'              => 'Paras Buildtech is a leading real estate developer delivering quality residential projects across North India since 2000. In the Tricity area, their Paras Panorama project in Kharar, Mohali offers premium 2 & 3 BHK apartments with modern design and comprehensive amenities.',
                'projects'                 => [
                    [
                        'title'            => 'Paras Panorama',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Kharar, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 480,
                        'available_units'  => 40,
                        'price_from'       => 4800000,
                        'price_to'         => 8500000,
                        'possession_date'  => '2021-03-31',
                        'rera_id'          => 'PBRERA-SAS80-PR0300',
                        'total_towers'     => 10,
                        'floors_per_tower' => '14',
                        'latitude'         => 30.7460,
                        'longitude'        => 76.7210,
                        'amenities'        => 'Swimming Pool,Clubhouse,Gymnasium,Jogging Track,Kids Play Area,Power Backup,24x7 Security,Landscaped Garden,Indoor Games,Amphitheatre',
                        'nearby_schools'   => 'Satluj Public School (2 km)',
                        'nearby_hospitals' => 'Fortis Hospital (8 km)',
                        'metro_distance'   => '12 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Paras Panorama in Kharar, Mohali is a premium residential project offering 2 & 3 BHK apartments (1280–1995 sqft) with high-quality construction and comprehensive amenities. Great connectivity to Chandigarh via the Kharar highway.',
                    ],
                    [
                        'title'            => 'Paras The Manor',
                        'project_type'     => 'Residential',
                        'status'           => 'Under Construction',
                        'address'          => 'Sector 115, Kharar, Mohali',
                        'city'             => 'Mohali',
                        'state'            => 'Punjab',
                        'total_units'      => 320,
                        'available_units'  => 160,
                        'price_from'       => 7500000,
                        'price_to'         => 13000000,
                        'possession_date'  => '2026-09-30',
                        'rera_id'          => 'PBRERA-SAS80-PR0360',
                        'total_towers'     => 8,
                        'floors_per_tower' => '16',
                        'latitude'         => 30.7520,
                        'longitude'        => 76.7130,
                        'amenities'        => 'Smart Home Features,Infinity Pool,Gymnasium,Yoga Deck,Kids Play Area,Power Backup,24x7 Security,High-Speed Elevators,EV Charging Points',
                        'nearby_schools'   => 'Chandigarh Group of Colleges (3 km)',
                        'nearby_hospitals' => 'Fortis Hospital (9 km)',
                        'metro_distance'   => '13 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Paras The Manor is a premium smart-home residential project in Sector 115, Kharar. Featuring home automation, infinity pool and modern architecture, it\'s designed for the discerning urban buyer. Possession September 2026.',
                    ],
                ],
            ],

            /* ── 8. Altus Space Builder ─────────────────────────────── */
            [
                'name'                     => 'Altus Space Builder',
                'company_name'             => 'Altus Space Builders Pvt. Ltd.',
                'email'                    => 'info@altusspace.in',
                'phone'                    => '+91 98882 88822',
                'website'                  => 'https://www.altusspace.in',
                'city'                     => 'Zirakpur',
                'established_year'         => '2012',
                'rera_registration'        => 'PBRERA-SAS79-PC0055',
                'cities_operating'         => 'Zirakpur,Mohali,Chandigarh',
                'rating'                   => 3.8,
                'is_verified'              => true,
                'total_delivered_projects' => 4,
                'description'              => 'Altus Space Builders specializes in premium commercial real estate in Zirakpur. Their Altus Space Towers project is one of Punjab\'s most successful commercial ventures, offering modern office spaces, co-working spaces and retail units with cutting-edge infrastructure and amenities.',
                'projects'                 => [
                    [
                        'title'            => 'Altus Space Towers',
                        'project_type'     => 'Commercial',
                        'status'           => 'Ready to Move',
                        'address'          => 'Airport Road, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 250,
                        'available_units'  => 40,
                        'price_from'       => 6500000,
                        'price_to'         => 22000000,
                        'possession_date'  => '2021-06-30',
                        'rera_id'          => 'PBRERA-SAS79-PC0055',
                        'total_towers'     => 2,
                        'floors_per_tower' => '14',
                        'latitude'         => 30.6570,
                        'longitude'        => 76.8250,
                        'amenities'        => 'High-Speed Elevators,Power Backup,24x7 Security,CCTV,Ample Parking,Conference Rooms,Food Court,ATM,High-Speed Internet,Rooftop Lounge',
                        'nearby_schools'   => null,
                        'nearby_hospitals' => 'Civil Hospital (3 km)',
                        'metro_distance'   => '4 km from Airport',
                        'is_featured'      => false,
                        'description'      => 'Altus Space Towers on Airport Road, Zirakpur is a premium commercial complex offering modern office spaces, co-working hubs and retail units. State-of-the-art infrastructure with high-speed internet, conference rooms and rooftop lounge.',
                    ],
                    [
                        'title'            => 'Altus Business Hub',
                        'project_type'     => 'Commercial',
                        'status'           => 'Under Construction',
                        'address'          => 'VIP Road, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 180,
                        'available_units'  => 120,
                        'price_from'       => 4500000,
                        'price_to'         => 15000000,
                        'possession_date'  => '2025-12-31',
                        'rera_id'          => 'PBRERA-SAS79-PC0070',
                        'total_towers'     => 1,
                        'floors_per_tower' => '12',
                        'latitude'         => 30.6445,
                        'longitude'        => 76.8165,
                        'amenities'        => 'High-Speed Elevators,Power Backup,CCTV,Security,Parking,Food Court,Conference Rooms',
                        'nearby_schools'   => null,
                        'nearby_hospitals' => 'Mukat Hospital (4 km)',
                        'metro_distance'   => '6 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Altus Business Hub on VIP Road, Zirakpur is a new commercial project offering affordable office and retail spaces. Ideal for startups, SMEs and retail brands seeking a prime VIP Road address.',
                    ],
                ],
            ],

            /* ── 9. Savitry Developers ──────────────────────────────── */
            [
                'name'                     => 'Savitry Developers',
                'company_name'             => 'Savitry Developers Pvt. Ltd.',
                'email'                    => 'info@savitrygreens.com',
                'phone'                    => '+91 98880 55566',
                'website'                  => 'https://www.savitrygreens.com',
                'city'                     => 'Zirakpur',
                'established_year'         => '2005',
                'rera_registration'        => 'PBRERA-SAS79-PR0420',
                'cities_operating'         => 'Zirakpur,Mohali,Panchkula',
                'rating'                   => 3.8,
                'is_verified'              => true,
                'total_delivered_projects' => 6,
                'description'              => 'Savitry Developers specializes in top-notch residential and commercial developments across Zirakpur and the Tricity area. Known for innovative design and quality construction, they deliver affordable homes with modern amenities. A trusted name in Zirakpur\'s real estate market since 2005.',
                'projects'                 => [
                    [
                        'title'            => 'Savitry Green Avenue',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Peer Mushalla, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 380,
                        'available_units'  => 35,
                        'price_from'       => 3200000,
                        'price_to'         => 6500000,
                        'possession_date'  => '2021-12-31',
                        'rera_id'          => 'PBRERA-SAS79-PR0420',
                        'total_towers'     => 8,
                        'floors_per_tower' => '10',
                        'latitude'         => 30.6530,
                        'longitude'        => 76.8290,
                        'amenities'        => 'Clubhouse,Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security,Landscaped Garden,Car Parking',
                        'nearby_schools'   => 'Satluj Public School (2 km)',
                        'nearby_hospitals' => 'Civil Hospital Zirakpur (3 km)',
                        'metro_distance'   => '8 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Savitry Green Avenue in Peer Mushalla, Zirakpur offers well-designed 2 & 3 BHK apartments with quality construction and essential amenities. A peaceful gated community ideal for families.',
                    ],
                    [
                        'title'            => 'Savitry Heights',
                        'project_type'     => 'Residential',
                        'status'           => 'Under Construction',
                        'address'          => 'Ambala Highway, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 280,
                        'available_units'  => 140,
                        'price_from'       => 4500000,
                        'price_to'         => 8000000,
                        'possession_date'  => '2026-06-30',
                        'rera_id'          => 'PBRERA-SAS79-PR0480',
                        'total_towers'     => 6,
                        'floors_per_tower' => '12',
                        'latitude'         => 30.6615,
                        'longitude'        => 76.8430,
                        'amenities'        => 'Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security,High-Speed Elevators,Party Lawn',
                        'nearby_schools'   => 'Chandigarh Business School (4 km)',
                        'nearby_hospitals' => 'Fortis Hospital (5 km)',
                        'metro_distance'   => '5 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Savitry Heights on Ambala Highway, Zirakpur offers premium 2 & 3 BHK apartments with modern architecture and quality construction. Under construction with June 2026 possession. RERA registered.',
                    ],
                ],
            ],

            /* ── 10. Green Valley Builders ──────────────────────────── */
            [
                'name'                     => 'Green Valley Builders',
                'company_name'             => 'Green Valley Builders & Developers',
                'email'                    => 'info@greenvalleybuilders.in',
                'phone'                    => '+91 98727 27272',
                'website'                  => 'https://www.greenvalleybuilders.in',
                'city'                     => 'Zirakpur',
                'established_year'         => '2008',
                'rera_registration'        => 'PBRERA-SAS79-PR0380',
                'cities_operating'         => 'Zirakpur,Panchkula,Mohali',
                'rating'                   => 3.7,
                'is_verified'              => false,
                'total_delivered_projects' => 5,
                'description'              => 'Green Valley Builders & Developers has been delivering quality residential projects in Zirakpur since 2008. Known for client satisfaction and honest dealings, they offer affordable 2 & 3 BHK apartments with essential amenities across strategic locations in Zirakpur and Panchkula.',
                'projects'                 => [
                    [
                        'title'            => 'Green Valley Township',
                        'project_type'     => 'Residential',
                        'status'           => 'Ready to Move',
                        'address'          => 'Patiala Highway, Zirakpur',
                        'city'             => 'Zirakpur',
                        'state'            => 'Punjab',
                        'total_units'      => 320,
                        'available_units'  => 30,
                        'price_from'       => 2800000,
                        'price_to'         => 5000000,
                        'possession_date'  => '2020-12-31',
                        'rera_id'          => 'PBRERA-SAS79-PR0380',
                        'total_towers'     => 8,
                        'floors_per_tower' => '8',
                        'latitude'         => 30.6420,
                        'longitude'        => 76.8140,
                        'amenities'        => 'Park,Kids Play Area,24x7 Security,Power Backup,Car Parking,CCTV,Community Hall',
                        'nearby_schools'   => 'Air Force Senior Secondary School (2 km)',
                        'nearby_hospitals' => 'Homecare Hospital (3 km)',
                        'metro_distance'   => '9 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Green Valley Township on Patiala Highway, Zirakpur offers budget-friendly 2 & 3 BHK apartments with essential amenities. A safe, secure gated community ideal for young families and first-time buyers.',
                    ],
                    [
                        'title'            => 'Green Valley Residency',
                        'project_type'     => 'Residential',
                        'status'           => 'Upcoming',
                        'address'          => 'Sector 20, Panchkula',
                        'city'             => 'Panchkula',
                        'state'            => 'Haryana',
                        'total_units'      => 200,
                        'available_units'  => 200,
                        'price_from'       => 4500000,
                        'price_to'         => 7500000,
                        'possession_date'  => '2027-03-31',
                        'rera_id'          => 'HRERA-PKL-450-2024',
                        'total_towers'     => 5,
                        'floors_per_tower' => '10',
                        'latitude'         => 30.7050,
                        'longitude'        => 76.8680,
                        'amenities'        => 'Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security',
                        'nearby_schools'   => 'DAV Public School (1.5 km)',
                        'nearby_hospitals' => 'Civil Hospital Panchkula (3 km)',
                        'metro_distance'   => '4 km from Chandigarh',
                        'is_featured'      => false,
                        'description'      => 'Green Valley Residency in Sector 20, Panchkula is an upcoming premium project offering 2 & 3 BHK apartments. Planned with modern amenities and excellent connectivity to Chandigarh. RERA registered. Bookings open.',
                    ],
                ],
            ],

        ]; // end $builders

        foreach ($builders as $data) {
            $projects = $data['projects'];
            unset($data['projects']);

            // Unique slug
            $baseSlug = Str::slug($data['company_name']);
            $slug = $baseSlug; $cnt = 1;
            while (DB::table('builders')->where('slug', $slug)->exists()) {
                $slug = $baseSlug . '-' . $cnt++;
            }

            // Skip duplicate emails
            if (DB::table('builders')->where('email', $data['email'])->exists()) {
                $this->command->warn("  [skip] {$data['company_name']} — already exists");
                $builderId = DB::table('builders')->where('email', $data['email'])->value('id');
            } else {
                $builderId = DB::table('builders')->insertGetId([
                    'name'                     => $data['name'],
                    'company_name'             => $data['company_name'],
                    'email'                    => $data['email'],
                    'password'                 => Hash::make('Builder@2024'),
                    'phone'                    => $data['phone'],
                    'website'                  => $data['website'],
                    'city'                     => $data['city'],
                    'established_year'         => $data['established_year'],
                    'description'              => $data['description'],
                    'rera_registration'        => $data['rera_registration'],
                    'cities_operating'         => $data['cities_operating'],
                    'rating'                   => $data['rating'],
                    'is_verified'              => $data['is_verified'],
                    'total_delivered_projects' => $data['total_delivered_projects'],
                    'status'                   => 'active',
                    'slug'                     => $slug,
                    'created_at'               => now(),
                    'updated_at'               => now(),
                ]);
                $this->command->line("  ✓ Builder: {$data['company_name']}");
            }

            foreach ($projects as $project) {
                if (DB::table('builder_projects')
                    ->where('builder_id', $builderId)
                    ->where('title', $project['title'])
                    ->exists()) {
                    $this->command->warn("    [skip] {$project['title']} — already exists");
                    continue;
                }

                DB::table('builder_projects')->insert([
                    'builder_id'       => $builderId,
                    'title'            => $project['title'],
                    'description'      => $project['description'],
                    'project_type'     => $project['project_type'],
                    'status'           => $project['status'],
                    'address'          => $project['address'],
                    'city'             => $project['city'],
                    'state'            => $project['state'],
                    'total_units'      => $project['total_units'],
                    'available_units'  => $project['available_units'],
                    'price_from'       => $project['price_from'],
                    'price_to'         => $project['price_to'],
                    'possession_date'  => $project['possession_date'],
                    'rera_id'          => $project['rera_id'] ?? null,
                    'total_towers'     => $project['total_towers'] ?? null,
                    'floors_per_tower' => $project['floors_per_tower'] ?? null,
                    'latitude'         => $project['latitude'] ?? null,
                    'longitude'        => $project['longitude'] ?? null,
                    'amenities'        => $project['amenities'],
                    'nearby_schools'   => $project['nearby_schools'] ?? null,
                    'nearby_hospitals' => $project['nearby_hospitals'] ?? null,
                    'metro_distance'   => $project['metro_distance'] ?? null,
                    'is_featured'      => $project['is_featured'],
                    'views_count'      => rand(80, 2000),
                    'leads_count'      => rand(5, 100),
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ]);
                $this->command->line("    ✓ Project: {$project['title']}");
            }
        }
    }
}
