<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class TricityRealDataSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('Seeding Tricity real estate data...');

        $this->seedBuilders();
        $this->seedDealers();

        $this->command->info('✅ All done!');
    }

    /* ============================================================
     *  BUILDERS
     * ============================================================ */
    private function seedBuilders(): void
    {
        $this->command->info('  → Seeding builders...');

        $builders = [
            [
                'name'                    => 'SBP Group',
                'company_name'            => 'SBP Group (Singla Builders And Promoters Ltd.)',
                'email'                   => 'digital@sbpgroup.in',
                'phone'                   => '+91 93160 04242',
                'website'                 => 'https://www.sbpgroup.in',
                'city'                    => 'Zirakpur',
                'established_year'        => '2007',
                'rera_registration'       => 'PBRERA-SAS79-PR1050',
                'cities_operating'        => 'Zirakpur,Mohali,Derabassi,Rajpura,Ludhiana',
                'rating'                  => 4.2,
                'is_verified'             => true,
                'total_delivered_projects'=> 28,
                'description'             => 'SBP Group (Singla Builders And Promoters) is the No. 1 housing company in Punjab, having delivered over 14,000 homes across 28+ completed projects. With 17+ years of excellence in the Tricity real estate market, they operate in Mohali, Zirakpur, Derabassi, Rajpura and Ludhiana. All projects are RERA-approved and built to the highest quality standards.',
                'projects'                => [
                    [
                        'title'           => 'SBP City of Dreams',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'High Ground Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 1200,
                        'available_units' => 450,
                        'price_from'      => 3500000,
                        'price_to'        => 9000000,
                        'possession_date' => '2026-05-30',
                        'rera_id'         => 'PBRERA-SAS79-PR0756',
                        'total_towers'    => 24,
                        'floors_per_tower'=> '3',
                        'latitude'        => 30.6480,
                        'longitude'       => 76.8190,
                        'amenities'       => 'Gymnasium,Swimming Pool,Power Backup,24x7 Security,Clubhouse,Basketball Court,Tennis Court,Kids Play Area,Jogging Track,Yoga Deck,Spa,Squash Court',
                        'nearby_schools'  => 'Delhi Public School (2 km), St. Mary\'s School (1.5 km)',
                        'nearby_hospitals'=> 'Fortis Hospital (4 km), Max Hospital (5 km)',
                        'metro_distance'  => '8 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'SBP City of Dreams offers premium 2 & 3 BHK apartments on High Ground Road, Zirakpur. Spread over 6.3 acres with a 20,000 sq.ft premium clubhouse featuring gym, pool, yoga and spa. Possession expected May 2026.',
                    ],
                    [
                        'title'           => 'SBP Housing Park',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Derabassi, SAS Nagar',
                        'city'            => 'Derabassi',
                        'state'           => 'Punjab',
                        'total_units'     => 2000,
                        'available_units' => 80,
                        'price_from'      => 2500000,
                        'price_to'        => 5500000,
                        'possession_date' => '2022-12-31',
                        'rera_id'         => 'PBRERA-SAS79-PR1050',
                        'total_towers'    => 40,
                        'floors_per_tower'=> '5',
                        'latitude'        => 30.5660,
                        'longitude'       => 76.8130,
                        'amenities'       => 'Children\'s Play Area,24x7 Security,Power Backup,CCTV Surveillance,Landscaped Park,Jogging Track,Community Hall',
                        'nearby_schools'  => 'Jawahar Navodaya Vidyalaya (3 km)',
                        'nearby_hospitals'=> 'Civil Hospital Derabassi (2 km)',
                        'metro_distance'  => '18 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'SBP Housing Park is one of the largest affordable housing projects in Punjab, delivering 2000+ homes to families in Derabassi. Well-designed 1 & 2 BHK apartments at competitive prices with essential amenities.',
                    ],
                ],
            ],

            [
                'name'                    => 'Sushma Buildtech',
                'company_name'            => 'Sushma Buildtech Pvt. Ltd.',
                'email'                   => 'info@sushma-builders.com',
                'phone'                   => '+91 85588 58811',
                'website'                 => 'https://www.sushma-builders.com',
                'city'                    => 'Zirakpur',
                'established_year'        => '2005',
                'rera_registration'       => 'PBRERA-SAS79-PR0084',
                'cities_operating'        => 'Zirakpur,Mohali,Chandigarh',
                'rating'                  => 4.3,
                'is_verified'             => true,
                'total_delivered_projects'=> 15,
                'description'             => 'Sushma Buildtech is one of the largest real estate developers in North India with 15+ RERA-registered projects across Zirakpur, Mohali and Chandigarh. Known for exceptional construction quality, on-time delivery and world-class amenities. Their portfolio ranges from affordable housing to ultra-luxury residences.',
                'projects'                => [
                    [
                        'title'           => 'Sushma Crescent',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Chaman Colony Road, Near Peer Baba Temple, Dhakoli, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 336,
                        'available_units' => 20,
                        'price_from'      => 4388000,
                        'price_to'        => 7973000,
                        'possession_date' => '2021-06-30',
                        'rera_id'         => 'PBRERA-SAS79-PR0084',
                        'total_towers'    => 16,
                        'floors_per_tower'=> '12',
                        'latitude'        => 30.6330,
                        'longitude'       => 76.8126,
                        'amenities'       => 'Swimming Pool,Clubhouse,Gymnasium,Jogging Track,Kids Play Area,Landscaped Gardens,24x7 Security,Power Backup,Intercom,Car Parking,Visitor Parking',
                        'nearby_schools'  => 'Ryan International School (1 km), St. Xavier\'s School (2 km)',
                        'nearby_hospitals'=> 'Mukat Hospital (3 km), Grecian Hospital (4 km)',
                        'metro_distance'  => '5 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'Sushma Crescent is a premium residential project in Dhakoli, Zirakpur offering 2, 3 and 4 BHK apartments across 9 towers on 7 acres. World-class amenities including clubhouse, swimming pool and manicured gardens. Ready to move.',
                    ],
                    [
                        'title'           => 'Sushma Grande NXT',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Airport Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 288,
                        'available_units' => 30,
                        'price_from'      => 4200000,
                        'price_to'        => 8500000,
                        'possession_date' => '2022-03-31',
                        'rera_id'         => 'PBRERA-SAS79-PR0082',
                        'total_towers'    => 8,
                        'floors_per_tower'=> '14',
                        'latitude'        => 30.6570,
                        'longitude'       => 76.8220,
                        'amenities'       => 'Swimming Pool,Gymnasium,Power Backup,24x7 Security,Kids Play Area,Jogging Track,Clubhouse,Indoor Games,Landscaped Garden',
                        'nearby_schools'  => 'Innocent Hearts School (1.5 km)',
                        'nearby_hospitals'=> 'Civil Hospital Zirakpur (2 km)',
                        'metro_distance'  => '4 km from Chandigarh Airport',
                        'is_featured'     => false,
                        'description'     => 'Sushma Grande NXT offers spacious 3 BHK apartments on Airport Road, Zirakpur. Premium construction quality with modern amenities and excellent connectivity to Chandigarh International Airport.',
                    ],
                    [
                        'title'           => 'Sushma Valencia',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'International Airport Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 432,
                        'available_units' => 200,
                        'price_from'      => 6000000,
                        'price_to'        => 12000000,
                        'possession_date' => '2025-12-31',
                        'rera_id'         => 'PBRERA-SAS80-PR0396',
                        'total_towers'    => 12,
                        'floors_per_tower'=> '14',
                        'latitude'        => 30.6600,
                        'longitude'       => 76.8250,
                        'amenities'       => 'Premium Clubhouse,Infinity Swimming Pool,Gymnasium,Tennis Court,Squash Court,Indoor Games,Party Lawn,Jogging Track,Kids Pool,Yoga Deck,Steam & Sauna,High-Speed Elevators',
                        'nearby_schools'  => 'Chandigarh Group of Colleges (2 km)',
                        'nearby_hospitals'=> 'Fortis Hospital (6 km)',
                        'metro_distance'  => '3 km from Airport',
                        'is_featured'     => true,
                        'description'     => 'Sushma Valencia is a luxury residential project on International Airport Road, Zirakpur. Premium 3 & 4 BHK apartments with world-class amenities and state-of-the-art infrastructure. Under construction with December 2025 possession.',
                    ],
                ],
            ],

            [
                'name'                    => 'Motia Group',
                'company_name'            => 'Motia Builders & Developers',
                'email'                   => 'info@motiagroup.com',
                'phone'                   => '+91 98155 98155',
                'website'                 => 'https://www.motiagroup.com',
                'city'                    => 'Zirakpur',
                'established_year'        => '2000',
                'rera_registration'       => 'PBRERA-SAS79-PC0001',
                'cities_operating'        => 'Zirakpur,Chandigarh,Mohali',
                'rating'                  => 4.1,
                'is_verified'             => true,
                'total_delivered_projects'=> 12,
                'description'             => 'Motia Group is a premier real estate company based in Zirakpur, renowned for outstanding residential and commercial constructions. Their flagship Motiaz Royal Citi is a self-sufficient integrated township on Chandigarh-Ambala Highway with schools, hospitals, retail malls and leisure spaces — a true community within a community.',
                'projects'                => [
                    [
                        'title'           => 'Motiaz Royal Citi',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Chandigarh-Ambala Highway, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 1000,
                        'available_units' => 50,
                        'price_from'      => 5000000,
                        'price_to'        => 9500000,
                        'possession_date' => '2020-06-30',
                        'rera_id'         => 'PBRERA-SAS79-PC0001',
                        'total_towers'    => 17,
                        'floors_per_tower'=> '13',
                        'latitude'        => 30.6520,
                        'longitude'       => 76.8500,
                        'amenities'       => 'Swimming Pool,Health Club,Jogging Track,24-Hour Water Supply,Power Backup,School,Hospital,Retail Mall,Leisure Spaces,Security,CCTV,Parking',
                        'nearby_schools'  => 'Motia International School (on campus)',
                        'nearby_hospitals'=> 'Motia Health Centre (on campus), Fortis Hospital (4 km)',
                        'metro_distance'  => '6 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'Motiaz Royal Citi is an iconic integrated township on Chandigarh-Ambala Highway. Spread across a vast area with 17 towers, it offers 3 BHK apartments, villas and commercial spaces with all urban conveniences within the campus.',
                    ],
                    [
                        'title'           => 'Motia Royal Business Park',
                        'project_type'    => 'Commercial',
                        'status'          => 'Ready to Move',
                        'address'         => 'Chandigarh-Ambala Highway, 4th Floor, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 200,
                        'available_units' => 30,
                        'price_from'      => 8000000,
                        'price_to'        => 25000000,
                        'possession_date' => '2019-01-01',
                        'rera_id'         => 'PBRERA-SAS79-PC0001',
                        'total_towers'    => 1,
                        'floors_per_tower'=> '12',
                        'latitude'        => 30.6525,
                        'longitude'       => 76.8505,
                        'amenities'       => 'High-Speed Elevators,Power Backup,24x7 Security,Ample Parking,Food Court,ATM,Conference Rooms,High-Speed Internet',
                        'nearby_schools'  => null,
                        'nearby_hospitals'=> null,
                        'metro_distance'  => '6 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'Motia Royal Business Park is a premium commercial development offering modern office spaces with cutting-edge infrastructure for businesses and startups in the heart of Zirakpur.',
                    ],
                ],
            ],

            [
                'name'                    => 'Gillco Group',
                'company_name'            => 'Gillco Group of Companies',
                'email'                   => 'info@gillcogroup.com',
                'phone'                   => '+91 98760 00200',
                'website'                 => 'https://www.gillcogroup.com',
                'city'                    => 'Mohali',
                'established_year'        => '2005',
                'rera_registration'       => 'PBRERA-SAS80-PR0038',
                'cities_operating'        => 'Mohali,Kharar,Chandigarh,Zirakpur',
                'rating'                  => 4.4,
                'is_verified'             => true,
                'total_delivered_projects'=> 8,
                'description'             => 'Established in 2005, Gillco Group is one of the most respected real estate developers in Punjab. Their flagship project Gillco Valley spans 400 acres in Sector 127, Mohali — one of the largest townships in the state. Known for consistent quality, on-time delivery and excellent post-sales service.',
                'projects'                => [
                    [
                        'title'           => 'Gillco Valley',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 127, Kharar-Landran Road, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 8000,
                        'available_units' => 200,
                        'price_from'      => 3000000,
                        'price_to'        => 8000000,
                        'possession_date' => '2018-12-31',
                        'rera_id'         => 'PBRERA-SAS80-PR0038',
                        'total_towers'    => 60,
                        'floors_per_tower'=> '14',
                        'latitude'        => 30.7553,
                        'longitude'       => 76.7340,
                        'amenities'       => 'Swimming Pool,Clubhouse,School,Hospital,Retail Mall,Gymnasium,Cricket Ground,Football Ground,Basketball Court,Tennis Court,Indoor Games,Jogging Track,24x7 Security',
                        'nearby_schools'  => 'Gillco International School (on campus), DAV Public School (2 km)',
                        'nearby_hospitals'=> 'Fortis Hospital (5 km), Civil Hospital (3 km)',
                        'metro_distance'  => '12 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'Gillco Valley is one of the largest townships in Mohali spanning 400 acres in Sector 127. A complete self-contained community with residential, commercial, educational and medical facilities — truly a city within a city.',
                    ],
                    [
                        'title'           => 'Gillco Parkhills',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Airport Road, Sector 126, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 700,
                        'available_units' => 40,
                        'price_from'      => 4139000,
                        'price_to'        => 9047000,
                        'possession_date' => '2022-06-30',
                        'rera_id'         => 'PBRERA-SAS81-PM0006',
                        'total_towers'    => 10,
                        'floors_per_tower'=> '19',
                        'latitude'        => 30.7030,
                        'longitude'       => 76.7510,
                        'amenities'       => 'Swimming Pool,Clubhouse,Gymnasium,Kids Play Area,Jogging Track,Power Backup,24x7 Security,Parking,Landscaped Gardens,CCTV',
                        'nearby_schools'  => 'Shivalik Public School (2 km)',
                        'nearby_hospitals'=> 'Max Super Speciality Hospital (4 km)',
                        'metro_distance'  => '3 km from Chandigarh Airport',
                        'is_featured'     => true,
                        'description'     => 'Gillco Parkhills offers premium 2, 3 and 4 BHK apartments in Sector 126, Mohali. Spread over 11.92 acres with 700 units across 10 high-rise towers near the International Airport.',
                    ],
                ],
            ],

            [
                'name'                    => 'Maya Builders',
                'company_name'            => 'Maya Builders & Developers',
                'email'                   => 'info@mayabuilders.in',
                'phone'                   => '+91 94170 19019',
                'website'                 => 'https://www.mayabuilders.in',
                'city'                    => 'Zirakpur',
                'established_year'        => '2003',
                'rera_registration'       => 'PBRERA-SAS79-PR0192',
                'cities_operating'        => 'Zirakpur,Patiala,Mohali',
                'rating'                  => 4.0,
                'is_verified'             => true,
                'total_delivered_projects'=> 10,
                'description'             => 'Maya Builders has been reshaping Zirakpur\'s skyline since 2003 with innovative and elegant residential complexes. Specializing in modern architecture that balances comfort, elegance and utility. Their Maya Garden City is one of Zirakpur\'s most iconic residential landmarks.',
                'projects'                => [
                    [
                        'title'           => 'Maya Garden City',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Lohgarh Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 1575,
                        'available_units' => 80,
                        'price_from'      => 5500000,
                        'price_to'        => 8000000,
                        'possession_date' => '2020-03-31',
                        'rera_id'         => 'PBRERA-SAS79-PR0192',
                        'total_towers'    => 47,
                        'floors_per_tower'=> '8',
                        'latitude'        => 30.6480,
                        'longitude'       => 76.8220,
                        'amenities'       => 'Security,Reserved Parking,Gymnasium,Lift,Power Backup,Intercom,Swimming Pool,Landscape Garden,Banquet Hall,24-Hour Water Supply,Kids Play Area,Meditation Area,Multipurpose Hall,Pool Table,Jogging Track',
                        'nearby_schools'  => 'Greenfield International School (1 km), Yadavindra Public School (3 km)',
                        'nearby_hospitals'=> 'Mukat Hospital (4 km), GMCH (8 km)',
                        'metro_distance'  => '7 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'Maya Garden City is a landmark residential township in Lohgarh, Zirakpur with 47 towers and 1575 units. Offering 2, 3 and 5 BHK flats in a fully developed community with world-class amenities. RERA approved and ready to move.',
                    ],
                    [
                        'title'           => 'Maya Garden Phase 3',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'VIP Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 800,
                        'available_units' => 60,
                        'price_from'      => 4200000,
                        'price_to'        => 6500000,
                        'possession_date' => '2019-12-31',
                        'rera_id'         => 'PBRERA-SAS79-PR0250',
                        'total_towers'    => 24,
                        'floors_per_tower'=> '8',
                        'latitude'        => 30.6450,
                        'longitude'       => 76.8180,
                        'amenities'       => '24x7 Security,Power Backup,Gymnasium,Swimming Pool,Kids Play Area,Jogging Track,Landscaped Gardens,Clubhouse,Car Parking',
                        'nearby_schools'  => 'Satluj Public School (1.5 km)',
                        'nearby_hospitals'=> 'Healing Hospital (3 km)',
                        'metro_distance'  => '7 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'Maya Garden Phase 3 offers well-planned 2 & 3 BHK apartments on VIP Road, Zirakpur. Quality construction with modern amenities at an affordable price point. Ready to move.',
                    ],
                ],
            ],

            [
                'name'                    => 'GBP Group',
                'company_name'            => 'GBP Group (Gupta Builders & Promoters)',
                'email'                   => 'info@gbpgroup.in',
                'phone'                   => '+91 98884 01234',
                'website'                 => 'https://www.gbpgroup.in',
                'city'                    => 'Mohali',
                'established_year'        => '2008',
                'rera_registration'       => 'PBRERA-SAS79-PR0400',
                'cities_operating'        => 'Mohali,Kharar,Zirakpur,Derabassi',
                'rating'                  => 3.9,
                'is_verified'             => true,
                'total_delivered_projects'=> 11,
                'description'             => 'GBP Group (Gupta Builders & Promoters) has delivered 11 projects across 150 acres with 5 ongoing projects. Serving 500+ families across Kharar, Derabassi and Zirakpur. Their GBP Athens luxury project on Ambala Highway is their premium flagship development.',
                'projects'                => [
                    [
                        'title'           => 'GBP Athens',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Ambala-Chandigarh Expressway, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 360,
                        'available_units' => 180,
                        'price_from'      => 7500000,
                        'price_to'        => 14000000,
                        'possession_date' => '2026-06-30',
                        'rera_id'         => 'PBRERA-SAS79-PR0521',
                        'total_towers'    => 8,
                        'floors_per_tower'=> '15',
                        'latitude'        => 30.6620,
                        'longitude'       => 76.8440,
                        'amenities'       => 'Infinity Pool,Sky Deck,Gymnasium,Spa,Concierge Service,Power Backup,EV Charging,High-Speed Elevators,Smart Home Features,Jogging Track',
                        'nearby_schools'  => 'Chandigarh Business School (3 km)',
                        'nearby_hospitals'=> 'Fortis Hospital (5 km)',
                        'metro_distance'  => '5 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'GBP Athens is a luxury residential project on the Ambala-Chandigarh Expressway, offering premium 3 & 4 BHK apartments with modern architecture. Features an infinity pool, sky deck, and cutting-edge smart home amenities.',
                    ],
                    [
                        'title'           => 'GBP Camellia',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Manali Highway, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 1200,
                        'available_units' => 100,
                        'price_from'      => 2800000,
                        'price_to'        => 5500000,
                        'possession_date' => '2021-03-31',
                        'rera_id'         => 'PBRERA-SAS79-PR0400',
                        'total_towers'    => 30,
                        'floors_per_tower'=> '7',
                        'latitude'        => 30.6400,
                        'longitude'       => 76.8100,
                        'amenities'       => 'Clubhouse,Swimming Pool,Park,Kids Play Area,24x7 Security,Power Backup,Gymnasium,Jogging Track,Community Hall',
                        'nearby_schools'  => 'Air Force Senior Secondary School (3 km)',
                        'nearby_hospitals'=> 'Homecare Hospital (2 km)',
                        'metro_distance'  => '9 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'GBP Camellia is a well-planned township spanning 22 acres on Manali Highway, Zirakpur. Affordable 2 & 3 BHK apartments with quality infrastructure and essential amenities for a comfortable community life.',
                    ],
                ],
            ],

            [
                'name'                    => 'Omaxe Ltd',
                'company_name'            => 'Omaxe Ltd.',
                'email'                   => 'info@omaxe.com',
                'phone'                   => '+91 1800 180 0222',
                'website'                 => 'https://www.omaxe.com',
                'city'                    => 'Chandigarh',
                'established_year'        => '1989',
                'rera_registration'       => 'PBRERA-SAS80-PR0034',
                'cities_operating'        => 'Chandigarh,Mohali,New Chandigarh,Delhi,Lucknow',
                'rating'                  => 3.8,
                'is_verified'             => true,
                'total_delivered_projects'=> 45,
                'description'             => 'Omaxe is one of India\'s leading real estate companies with a presence across 27+ cities. Their 800-acre integrated township at New Chandigarh (Mullanpur) is among the most ambitious real estate developments in the Tricity region, offering plots, floors, villas and apartments.',
                'projects'                => [
                    [
                        'title'           => 'Omaxe The Lake',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Mullanpur, New Chandigarh',
                        'city'            => 'Chandigarh',
                        'state'           => 'Punjab',
                        'total_units'     => 1345,
                        'available_units' => 100,
                        'price_from'      => 7000000,
                        'price_to'        => 18000000,
                        'possession_date' => '2021-12-31',
                        'rera_id'         => 'PBRERA-SAS80-PR0040',
                        'total_towers'    => 16,
                        'floors_per_tower'=> '19',
                        'latitude'        => 30.8245,
                        'longitude'       => 76.7700,
                        'amenities'       => 'Lake View,Clubhouse,Swimming Pool,Gymnasium,Jogging Track,Tennis Court,Squash Court,Kids Play Area,24x7 Security,Power Backup,Amphitheatre',
                        'nearby_schools'  => 'Gurukul Vidyapeeth (3 km)',
                        'nearby_hospitals'=> 'PGI Chandigarh (8 km)',
                        'metro_distance'  => '10 km from Chandigarh',
                        'is_featured'     => true,
                        'description'     => 'Omaxe The Lake at Mullanpur (New Chandigarh) offers luxurious 2, 3 and 4 BHK lake-view apartments. Spread over 25 acres with 16 high-rise towers. Premium lifestyle destination close to PGI Chandigarh.',
                    ],
                    [
                        'title'           => 'Omaxe New Chandigarh Plots',
                        'project_type'    => 'Plotted',
                        'status'          => 'Ready to Move',
                        'address'         => 'Mullanpur, New Chandigarh',
                        'city'            => 'Chandigarh',
                        'state'           => 'Punjab',
                        'total_units'     => 2000,
                        'available_units' => 150,
                        'price_from'      => 2500000,
                        'price_to'        => 15000000,
                        'possession_date' => '2020-01-01',
                        'rera_id'         => 'PBRERA-SAS80-PR0034',
                        'total_towers'    => null,
                        'floors_per_tower'=> null,
                        'latitude'        => 30.8240,
                        'longitude'       => 76.7695,
                        'amenities'       => 'Wide Internal Roads,Underground Drainage,24x7 Security,Electricity Connection,Parks,Community Centre',
                        'nearby_schools'  => 'DPS (upcoming), Yadavindra Public School (5 km)',
                        'nearby_hospitals'=> 'PGI Chandigarh (8 km)',
                        'metro_distance'  => 'Metro corridor (upcoming)',
                        'is_featured'     => false,
                        'description'     => 'Omaxe New Chandigarh offers residential plots from 115 to 1000 sq yards in a planned 800-acre integrated township. Close to upcoming metro line, bus terminal and PGI Chandigarh. RERA registered.',
                    ],
                ],
            ],

            [
                'name'                    => 'TDI Infrastructure',
                'company_name'            => 'TDI Infrastructure Ltd.',
                'email'                   => 'info@tdigroup.net',
                'phone'                   => '+91 97736 33634',
                'website'                 => 'https://www.tdiinfratech.com',
                'city'                    => 'Panchkula',
                'established_year'        => '1997',
                'rera_registration'       => 'HRERA-PKL-229-2017',
                'cities_operating'        => 'Panchkula,Zirakpur,Delhi,Mohali',
                'rating'                  => 3.7,
                'is_verified'             => false,
                'total_delivered_projects'=> 20,
                'description'             => 'TDI Infrastructure Ltd. has been delivering quality residential and commercial developments since 1997. They operate across Panchkula and Zirakpur with residential plots, villas and floors. Known for well-planned layouts and excellent connectivity to the Tricity area.',
                'projects'                => [
                    [
                        'title'           => 'TDI Rosewood City',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 14, Panchkula',
                        'city'            => 'Panchkula',
                        'state'           => 'Haryana',
                        'total_units'     => 600,
                        'available_units' => 45,
                        'price_from'      => 5500000,
                        'price_to'        => 9000000,
                        'possession_date' => '2019-06-30',
                        'rera_id'         => 'HRERA-PKL-229-2017',
                        'total_towers'    => 15,
                        'floors_per_tower'=> '12',
                        'latitude'        => 30.7046,
                        'longitude'       => 76.8636,
                        'amenities'       => 'Clubhouse,Swimming Pool,Gymnasium,Kids Play Area,Jogging Track,24x7 Security,Power Backup,Landscaped Gardens,Multi-Purpose Hall',
                        'nearby_schools'  => 'DAV Centenary Public School (2 km)',
                        'nearby_hospitals'=> 'Civil Hospital Panchkula (3 km)',
                        'metro_distance'  => '4 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'TDI Rosewood City in Sector 14, Panchkula offers well-designed 2 & 3 BHK apartments with excellent connectivity to Chandigarh. Modern amenities and green surroundings make it an ideal residence.',
                    ],
                    [
                        'title'           => 'TDI Plots Zirakpur',
                        'project_type'    => 'Plotted',
                        'status'          => 'Ready to Move',
                        'address'         => 'VIP Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 400,
                        'available_units' => 60,
                        'price_from'      => 2000000,
                        'price_to'        => 8000000,
                        'possession_date' => '2018-12-31',
                        'rera_id'         => 'PBRERA-SAS79-PR0350',
                        'total_towers'    => null,
                        'floors_per_tower'=> null,
                        'latitude'        => 30.6490,
                        'longitude'       => 76.8160,
                        'amenities'       => 'Wide Internal Roads,Electricity Connection,Underground Drainage,24x7 Security,Parks,Street Lighting',
                        'nearby_schools'  => 'Shivalik Montessori School (2 km)',
                        'nearby_hospitals'=> 'Healing Hospital (3 km)',
                        'metro_distance'  => '6 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'TDI Residential Plots on VIP Road, Zirakpur in sizes from 200 to 500 sq yards. Excellent connectivity to all Tricity locations. Ideal for investment or self-construction.',
                    ],
                ],
            ],

            [
                'name'                    => 'Green Lotus Group',
                'company_name'            => 'Green Lotus Group',
                'email'                   => 'info@greenlotusgroup.com',
                'phone'                   => '+91 98789 80808',
                'website'                 => 'https://www.greenlotusgroup.com',
                'city'                    => 'Zirakpur',
                'established_year'        => '2010',
                'rera_registration'       => 'PBRERA-SAS79-PR0320',
                'cities_operating'        => 'Zirakpur,Mohali',
                'rating'                  => 4.5,
                'is_verified'             => true,
                'total_delivered_projects'=> 6,
                'description'             => 'Green Lotus Group is Zirakpur\'s leading eco-friendly builder, combining innovative design with green technologies. They create energy-efficient residential and commercial spaces with a focus on environmental conservation, solar panels, rainwater harvesting and sustainable materials.',
                'projects'                => [
                    [
                        'title'           => 'Green Lotus Saksham',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Airport Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 450,
                        'available_units' => 35,
                        'price_from'      => 3800000,
                        'price_to'        => 7200000,
                        'possession_date' => '2021-09-30',
                        'rera_id'         => 'PBRERA-SAS79-PR0320',
                        'total_towers'    => 10,
                        'floors_per_tower'=> '12',
                        'latitude'        => 30.6510,
                        'longitude'       => 76.8180,
                        'amenities'       => 'Solar Energy System,Rainwater Harvesting,Green Landscaping,Gymnasium,Swimming Pool,Kids Play Area,Jogging Track,Power Backup,24x7 Security,EV Charging',
                        'nearby_schools'  => 'Lotus International School (0.5 km)',
                        'nearby_hospitals'=> 'Mukat Hospital (3 km)',
                        'metro_distance'  => '4 km from Chandigarh Airport',
                        'is_featured'     => true,
                        'description'     => 'Green Lotus Saksham is Zirakpur\'s most eco-friendly residential project on Airport Road. Energy-efficient green building with solar panels, rainwater harvesting and lush landscapes. 2 & 3 BHK apartments. Ready to move.',
                    ],
                    [
                        'title'           => 'Green Lotus Avenue',
                        'project_type'    => 'Commercial',
                        'status'          => 'Ready to Move',
                        'address'         => 'VIP Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 150,
                        'available_units' => 25,
                        'price_from'      => 5000000,
                        'price_to'        => 20000000,
                        'possession_date' => '2020-06-30',
                        'rera_id'         => 'PBRERA-SAS79-PC0040',
                        'total_towers'    => 1,
                        'floors_per_tower'=> '8',
                        'latitude'        => 30.6440,
                        'longitude'       => 76.8155,
                        'amenities'       => 'High-Speed Elevators,Power Backup,CCTV,24x7 Security,Ample Parking,Green Spaces,Food Court',
                        'nearby_schools'  => null,
                        'nearby_hospitals'=> null,
                        'metro_distance'  => '6 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'Green Lotus Avenue is a premium eco-friendly commercial complex on VIP Road, Zirakpur. Modern office and retail spaces with green architecture, ample parking and excellent connectivity.',
                    ],
                ],
            ],

            [
                'name'                    => 'Bestech Group',
                'company_name'            => 'Bestech India Pvt. Ltd.',
                'email'                   => 'info@bestechgroup.com',
                'phone'                   => '+91 98882 00200',
                'website'                 => 'https://www.bestechgroup.com',
                'city'                    => 'Mohali',
                'established_year'        => '1993',
                'rera_registration'       => 'PBRERA-SAS80-PR0200',
                'cities_operating'        => 'Mohali,Gurgaon,Chandigarh',
                'rating'                  => 4.2,
                'is_verified'             => true,
                'total_delivered_projects'=> 22,
                'description'             => 'Bestech Group is a real estate conglomerate founded by Mr. Dharmendra Bhandari with over three decades of expertise in residential, commercial, retail and hospitality. Delivered 4.5 million sq.ft in Gurgaon with 7 million sq.ft under development in Gurgaon and Mohali.',
                'projects'                => [
                    [
                        'title'           => 'Bestech Park View Residences',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 66, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 186,
                        'available_units' => 15,
                        'price_from'      => 8000000,
                        'price_to'        => 15000000,
                        'possession_date' => '2019-01-01',
                        'rera_id'         => null,
                        'total_towers'    => 8,
                        'floors_per_tower'=> '14',
                        'latitude'        => 30.6994,
                        'longitude'       => 76.6918,
                        'amenities'       => 'Children\'s Play Area,Park,Amphitheatre,Jogging Track,Party Lawn,Car Parking,Swimming Pool,Gymnasium,Club House',
                        'nearby_schools'  => 'Strawberry Fields High School (2 km)',
                        'nearby_hospitals'=> 'Fortis Hospital Mohali (3 km)',
                        'metro_distance'  => '5 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'Bestech Park View Residences in Sector 66, Mohali is a premium luxury residential project. Part of the 12.5-acre multi-functional Bestech Square complex, just 5 minutes from Chandigarh. Offers 2 & 3 BHK luxury apartments.',
                    ],
                    [
                        'title'           => 'Bestech Business Tower',
                        'project_type'    => 'Commercial',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 66, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 120,
                        'available_units' => 20,
                        'price_from'      => 10000000,
                        'price_to'        => 30000000,
                        'possession_date' => '2020-01-01',
                        'rera_id'         => 'PBRERA-SAS80-PR0200',
                        'total_towers'    => 1,
                        'floors_per_tower'=> '18',
                        'latitude'        => 30.6992,
                        'longitude'       => 76.6920,
                        'amenities'       => 'High-Speed Elevators,Power Backup,24x7 Security,Ample Parking,Food Court,Conference Rooms,ATM,High-Speed Internet',
                        'nearby_schools'  => null,
                        'nearby_hospitals'=> null,
                        'metro_distance'  => '5 km from Chandigarh',
                        'is_featured'     => false,
                        'description'     => 'Bestech Business Tower is a premium Grade-A commercial project in Sector 66, Mohali offering modern office spaces for corporates, IT companies and businesses.',
                    ],
                ],
            ],
        ];

        foreach ($builders as $data) {
            $projects = $data['projects'];
            unset($data['projects']);

            // Generate slug
            $baseSlug = Str::slug($data['company_name']);
            $slug = $baseSlug;
            $count = 1;
            while (DB::table('builders')->where('slug', $slug)->exists()) {
                $slug = $baseSlug . '-' . $count++;
            }

            // Check if email already exists
            if (DB::table('builders')->where('email', $data['email'])->exists()) {
                $this->command->warn("  [skip builder] {$data['company_name']} — email already exists");
                // Get the builder id to insert projects
                $builderId = DB::table('builders')->where('email', $data['email'])->value('id');
            } else {
                $builderId = DB::table('builders')->insertGetId([
                    'name'                     => $data['name'],
                    'company_name'             => $data['company_name'],
                    'email'                    => $data['email'],
                    'password'                 => Hash::make('Builder@2024'),
                    'phone'                    => $data['phone'],
                    'website'                  => $data['website'],
                    'city'                     => $data['city'],
                    'established_year'         => $data['established_year'],
                    'description'              => $data['description'],
                    'rera_registration'        => $data['rera_registration'],
                    'cities_operating'         => $data['cities_operating'],
                    'rating'                   => $data['rating'],
                    'is_verified'              => $data['is_verified'],
                    'total_delivered_projects' => $data['total_delivered_projects'],
                    'status'                   => 'active',
                    'slug'                     => $slug,
                    'created_at'               => now(),
                    'updated_at'               => now(),
                ]);
                $this->command->line("  ✓ Builder: {$data['company_name']}");
            }

            // Insert projects for this builder
            foreach ($projects as $project) {
                // Check if project title already exists for this builder
                if (DB::table('builder_projects')
                    ->where('builder_id', $builderId)
                    ->where('title', $project['title'])
                    ->exists()) {
                    $this->command->warn("    [skip project] {$project['title']} — already exists");
                    continue;
                }

                DB::table('builder_projects')->insert([
                    'builder_id'       => $builderId,
                    'title'            => $project['title'],
                    'description'      => $project['description'],
                    'project_type'     => $project['project_type'],
                    'status'           => $project['status'],
                    'address'          => $project['address'],
                    'city'             => $project['city'],
                    'state'            => $project['state'],
                    'total_units'      => $project['total_units'],
                    'available_units'  => $project['available_units'],
                    'price_from'       => $project['price_from'],
                    'price_to'         => $project['price_to'],
                    'possession_date'  => $project['possession_date'],
                    'rera_id'          => $project['rera_id'] ?? null,
                    'total_towers'     => $project['total_towers'] ?? null,
                    'floors_per_tower' => $project['floors_per_tower'] ?? null,
                    'latitude'         => $project['latitude'] ?? null,
                    'longitude'        => $project['longitude'] ?? null,
                    'amenities'        => $project['amenities'],
                    'nearby_schools'   => $project['nearby_schools'] ?? null,
                    'nearby_hospitals' => $project['nearby_hospitals'] ?? null,
                    'metro_distance'   => $project['metro_distance'] ?? null,
                    'is_featured'      => $project['is_featured'],
                    'views_count'      => rand(100, 1500),
                    'leads_count'      => rand(5, 80),
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ]);
                $this->command->line("    ✓ Project: {$project['title']}");
            }
        }
    }

    /* ============================================================
     *  DEALERS
     * ============================================================ */
    private function seedDealers(): void
    {
        $this->command->info('  → Seeding dealers...');

        $dealers = [
            [
                'first_name'       => 'Rahul',
                'last_name'        => 'Sharma',
                'company_name'     => 'People\'s Property Point',
                'phone'            => '+91 76965 51555',
                'email'            => 'peoplespropertypoint@gmail.com',
                'bio'              => 'One of the most trusted property dealers in Zirakpur with 1000+ properties listed across Tricity. Specializing in residential and commercial properties in Zirakpur, Mohali, Panchkula and Chandigarh. Over 15 years of market experience.',
                'specializations'  => 'Residential Flats,Apartments,Villas,Plots',
                'operating_cities' => 'Zirakpur,Mohali,Panchkula,Chandigarh',
            ],
            [
                'first_name'       => 'Anil',
                'last_name'        => 'Taneja',
                'company_name'     => 'Taneja Property Consultants',
                'phone'            => '+91 98765 43210',
                'email'            => 'anil@tanejapropertyconsultants.com',
                'bio'              => 'Founded in 2008, Taneja Property Consultants has built a wide network in Zirakpur and surrounding areas. Expert in residential flats, builder floors and commercial properties with transparent dealings.',
                'specializations'  => 'Residential,Builder Floors,Commercial',
                'operating_cities' => 'Zirakpur,Chandigarh,Mohali',
            ],
            [
                'first_name'       => 'Rajiv',
                'last_name'        => 'Malhotra',
                'company_name'     => 'Home Search Real Estate',
                'phone'            => '+91 98720 09125',
                'email'            => 'rajiv@homesearchzirakpur.com',
                'bio'              => 'Established in 2004, Home Search is a well-known real estate agency near GMADA Aerocity. Specializing in airport-zone properties, plots and residential apartments. Serving satisfied clients for 20+ years.',
                'specializations'  => 'Residential,Aerocity Properties,Plots',
                'operating_cities' => 'Mohali,Zirakpur,Chandigarh',
            ],
            [
                'first_name'       => 'Suresh',
                'last_name'        => 'Verma',
                'company_name'     => 'Value Homes Real Estate',
                'phone'            => '+91 99884 00888',
                'email'            => 'valuehomeszirakpur@gmail.com',
                'bio'              => 'Value Homes offers the best deals in Zirakpur\'s real estate market. Experts in budget homes, resale flats and new bookings across Tricity. Committed to helping you find the best property at the best price.',
                'specializations'  => 'Budget Homes,Resale Flats,New Bookings',
                'operating_cities' => 'Zirakpur,Panchkula,Mohali',
            ],
            [
                'first_name'       => 'Gurpreet',
                'last_name'        => 'Singh',
                'company_name'     => 'Sidham Properties',
                'phone'            => '+91 99887 75143',
                'email'            => 'sidhamproperties@gmail.com',
                'bio'              => 'Sidham Properties is a leading real estate consultancy on Patiala Highway, Zirakpur. Trusted by thousands of clients for transparent dealings and professional property advice across Tricity.',
                'specializations'  => 'Residential Flats,Plots,Commercial Properties',
                'operating_cities' => 'Zirakpur,Panchkula,Chandigarh',
            ],
            [
                'first_name'       => 'Vikram',
                'last_name'        => 'Arora',
                'company_name'     => 'Ekav Estate',
                'phone'            => '+91 91155 52555',
                'email'            => 'info@ekavestate.com',
                'bio'              => 'Ekav Estate is a modern real estate consultancy located in Green Lotus Avenue, Zirakpur. Offering expert advice on buying, selling and renting residential and commercial properties across Tricity.',
                'specializations'  => 'Residential,Commercial,Rental Properties',
                'operating_cities' => 'Zirakpur,Mohali,Chandigarh',
            ],
            [
                'first_name'       => 'Pankaj',
                'last_name'        => 'Garg',
                'company_name'     => 'Paridhi - The Real Estate Agency',
                'phone'            => '+91 98882 23322',
                'email'            => 'info@paridhi.org',
                'bio'              => 'Paridhi is one of Zirakpur\'s top 5 property dealers dealing in sale, purchase and rent of flats, houses, plots, shops and showrooms across Zirakpur, Aerocity, Panchkula, Chandigarh and Mohali.',
                'specializations'  => 'Flats,Houses,Plots,Shops,Showrooms',
                'operating_cities' => 'Zirakpur,Aerocity,Panchkula,Chandigarh,Mohali',
            ],
            [
                'first_name'       => 'Deepak',
                'last_name'        => 'Kumar',
                'company_name'     => 'Smart Move Realty Pvt. Ltd.',
                'phone'            => '+91 98151 07112',
                'email'            => 'smartmoverealty.mohali@gmail.com',
                'bio'              => 'Smart Move Realty is a professional real estate company in GMADA Aerocity, Mohali. Specializing in premium properties, aerocity apartments and commercial spaces. Trusted by investors and home buyers alike.',
                'specializations'  => 'Premium Properties,Aerocity,Commercial',
                'operating_cities' => 'Mohali,Zirakpur,Chandigarh',
            ],
            [
                'first_name'       => 'Sanjay',
                'last_name'        => 'Mehta',
                'company_name'     => 'DNA Realtors Panchkula',
                'phone'            => '+91 98760 09876',
                'email'            => 'dnarealtors.panchkula@gmail.com',
                'bio'              => 'DNA Realtors was founded in 2010 and has helped hundreds of clients locate their dream residences and commercial spaces in Panchkula and surrounding areas. Known for honest dealings and expert local market knowledge.',
                'specializations'  => 'Residential,Plots,Commercial Spaces',
                'operating_cities' => 'Panchkula,Zirakpur,Chandigarh,Mohali',
            ],
            [
                'first_name'       => 'Rohit',
                'last_name'        => 'Batra',
                'company_name'     => 'Batra Estate Panchkula',
                'phone'            => '+91 98140 98140',
                'email'            => 'rohitbatra@batraestatepanchkula.com',
                'bio'              => 'Established in 2007, Batra Estate is one of the top property dealers in Panchkula. Expert in residential and commercial transactions with a strong network across Panchkula sectors and Tricity areas.',
                'specializations'  => 'Residential Flats,Builder Floors,Commercial',
                'operating_cities' => 'Panchkula,Mohali,Chandigarh',
            ],
            [
                'first_name'       => 'Manpreet',
                'last_name'        => 'Singh',
                'company_name'     => 'CREx Property Consultants',
                'phone'            => '+91 98174 00037',
                'email'            => 'info@crexproperty.com',
                'bio'              => 'CREx Property is a top real estate agency in Zirakpur offering comprehensive property services including buyer representation, seller services and investment advisory across Tricity.',
                'specializations'  => 'Buyer Representation,Seller Services,Investment Advice',
                'operating_cities' => 'Zirakpur,Chandigarh,Mohali,Panchkula',
            ],
            [
                'first_name'       => 'Harjinder',
                'last_name'        => 'Gill',
                'company_name'     => 'Manglam Real Estate',
                'phone'            => '+91 98721 12345',
                'email'            => 'manglam.realestate.zrk@gmail.com',
                'bio'              => 'Manglam Real Estate is based at Peer Mushalla, Zirakpur with deep local market expertise. Specialists in residential and commercial properties, land acquisition and investment advisory for Zirakpur and Mohali.',
                'specializations'  => 'Residential,Commercial,Land & Plots',
                'operating_cities' => 'Zirakpur,Mohali',
            ],
            [
                'first_name'       => 'Amarjit',
                'last_name'        => 'Sandhu',
                'company_name'     => 'The Property Time',
                'phone'            => '+91 98150 43210',
                'email'            => 'thepropertytime.zrk@gmail.com',
                'bio'              => 'Founded in 1995, The Property Time is one of the oldest and most trusted real estate agencies in Zirakpur. Serving clients for 30 years across Panchkula, Mohali, Zirakpur and Chandigarh with 5000+ successful transactions.',
                'specializations'  => 'Residential,Commercial,Plots,Industrial',
                'operating_cities' => 'Zirakpur,Panchkula,Mohali,Chandigarh',
            ],
            [
                'first_name'       => 'Navdeep',
                'last_name'        => 'Kaur',
                'company_name'     => 'Reconsult Advisory Services',
                'phone'            => '+91 98889 01234',
                'email'            => 'info@reconsultadvisory.in',
                'bio'              => 'Reconsult Advisory Services provides expert real estate consulting for plots, villas and apartments in Zirakpur and Tricity. Specializing in buy, rent and lease services with a client-first approach.',
                'specializations'  => 'Plots,Villas,Apartments,Lease Services',
                'operating_cities' => 'Zirakpur,Mohali,Chandigarh',
            ],
            [
                'first_name'       => 'Kamal',
                'last_name'        => 'Kapoor',
                'company_name'     => 'Tricity Properties',
                'phone'            => '+91 78378 78378',
                'email'            => 'tricityproperties.chd@gmail.com',
                'bio'              => 'Tricity Properties is a full-service real estate agency covering Chandigarh, Mohali and Panchkula. Expert in luxury apartments, IT park office spaces and investment-grade properties for NRI and local buyers.',
                'specializations'  => 'Luxury Apartments,IT Park Offices,NRI Services',
                'operating_cities' => 'Chandigarh,Mohali,Panchkula,Zirakpur',
            ],
        ];

        foreach ($dealers as $dealer) {
            if (DB::table('property_dealers')->where('email', $dealer['email'])->exists()) {
                $this->command->warn("  [skip dealer] {$dealer['first_name']} {$dealer['last_name']} — email already exists");
                continue;
            }

            // Generate slug from name
            $baseName = trim($dealer['first_name'] . ' ' . $dealer['last_name']);
            $slug = Str::slug($baseName);
            $original = $slug; $cnt = 1;
            while (DB::table('property_dealers')->where('slug', $slug)->exists()) {
                $slug = $original . '-' . $cnt++;
            }

            DB::table('property_dealers')->insert([
                'slug'             => $slug,
                'first_name'       => $dealer['first_name'],
                'last_name'        => $dealer['last_name'],
                'company_name'     => $dealer['company_name'],
                'phone'            => $dealer['phone'],
                'email'            => $dealer['email'],
                'password'         => Hash::make('Dealer@2024'),
                'bio'              => $dealer['bio'],
                'specializations'  => $dealer['specializations'],
                'operating_cities' => $dealer['operating_cities'],
                'status'           => 'active',
                'created_at'       => now(),
                'updated_at'       => now(),
            ]);
            $this->command->line("  ✓ Dealer: {$dealer['first_name']} {$dealer['last_name']} — {$dealer['company_name']}");
        }
    }
}
