<?php

namespace Database\Seeders;

use App\Models\Builder;
use App\Models\BuilderProject;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * TricityBuilderSeeder
 *
 * Real builder data scraped from public sources for the Chandigarh Tricity region
 * (Chandigarh, Mohali, Zirakpur, Panchkula, Kharar, Derabassi, Mullanpur — all within 100 km).
 *
 * Sources: builder websites, 99acres, MagicBricks, Punjab RERA, JustDial (July 2026)
 * Run: php artisan db:seed --class=TricityBuilderSeeder
 */
class TricityBuilderSeeder extends Seeder
{
    public function run(): void
    {
        $builders = $this->builderData();

        foreach ($builders as $data) {
            $projects = $data['projects'];
            unset($data['projects']);

            $builder = Builder::firstOrCreate(
                ['email' => $data['email']],
                array_merge($data, ['password' => Hash::make('Builder@2026')])
            );

            foreach ($projects as $project) {
                BuilderProject::firstOrCreate(
                    ['builder_id' => $builder->id, 'title' => $project['title']],
                    array_merge($project, ['builder_id' => $builder->id])
                );
            }

            $this->command->info("✓ {$builder->company_name} — " . count($projects) . " project(s)");
        }

        $this->command->info('');
        $this->command->info('TricityBuilderSeeder completed — ' . count($builders) . ' builders seeded.');
        $this->command->info('Default login password: Builder@2026');
    }

    private function builderData(): array
    {
        return [

            // ─── 1. SBP Group ───────────────────────────────────────────────
            [
                'name'                     => 'Aman Singla',
                'company_name'             => 'SBP Group',
                'email'                    => 'digital@sbpgroup.in',
                'phone'                    => '9316004242',
                'website'                  => 'https://www.sbpgroup.in',
                'city'                     => 'Mohali',
                'established_year'         => '2006',
                'rera_registration'        => 'PBRERA-SAS79-PR1050',
                'cities_operating'         => 'Mohali, Zirakpur, Derabassi, Kharar',
                'total_delivered_projects' => 28,
                'rating'                   => 4.4,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'SBP Group is one of the most trusted real estate developers in the Chandigarh Tricity region with 18+ years of experience. Based in Mohali, they have delivered over 28 RERA-approved residential projects with 15,000+ happy families across Mohali, Zirakpur and Derabassi. Home loan partners include HDFC and SBI.',
                'projects' => [
                    [
                        'title'           => 'SBP City of Dreams',
                        'description'     => 'A flagship township in Mohali Sector 127 offering premium 2 & 3 BHK flats with exceptional lifestyle amenities. Strategically located on Kharar Banur Road with excellent connectivity.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Sector 127, Kharar Banur Road',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 388,
                        'available_units' => 120,
                        'price_from'      => 4200000,
                        'price_to'        => 7500000,
                        'possession_date' => '2026-12-31',
                        'amenities'       => 'Clubhouse, Swimming Pool, Gym, Jogging Track, Kids Play Area, 24/7 Security, Power Backup, CCTV, Covered Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR1050',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'SBP Housing Park Derabassi',
                        'description'     => 'Premium residential township on the Ambala Chandigarh Expressway offering plots and independent floors in the fast-growing Derabassi micro-market.',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Central Derabassi, Ambala Chandigarh Expressway',
                        'city'            => 'Derabassi',
                        'state'           => 'Punjab',
                        'total_units'     => 380,
                        'available_units' => 45,
                        'price_from'      => 2800000,
                        'price_to'        => 5500000,
                        'possession_date' => '2025-06-30',
                        'amenities'       => 'Landscaped Gardens, Community Hall, Sports Complex, 24/7 Security, Wide Internal Roads',
                        'rera_id'         => 'PBRERA-SAS79-PR0889',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'SBP Nature City Kharar',
                        'description'     => 'Eco-friendly gated community in Central Kharar offering 1394 units of 2 & 3 BHK apartments. Only 1.6 km from Chandigarh Road, ideal for families seeking green living.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Central Kharar, Near Chandigarh Road',
                        'city'            => 'Kharar',
                        'state'           => 'Punjab',
                        'total_units'     => 1394,
                        'available_units' => 80,
                        'price_from'      => 3500000,
                        'price_to'        => 6200000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Swimming Pool, Gym, Badminton Court, Yoga Deck, Kids Zone, ATM, Mini Mart, Power Backup',
                        'rera_id'         => 'PBRERA-SAS79-PR0742',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 2. GBP Group (Gupta Builders & Promoters) ──────────────────
            [
                'name'                     => 'Satish Gupta',
                'company_name'             => 'GBP Group (Gupta Builders & Promoters)',
                'email'                    => 'sales@gbpgroup.in',
                'phone'                    => '9569545454',
                'website'                  => 'https://www.gbpgroup.in',
                'city'                     => 'Chandigarh',
                'established_year'         => '2009',
                'rera_registration'        => 'PBRERA-SAS79-PR0612',
                'cities_operating'         => 'Chandigarh, Mohali, Derabassi, Zirakpur, Kharar',
                'total_delivered_projects' => 18,
                'rating'                   => 4.3,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'GBP Group is one of the leading real estate builders in Chandigarh Tricity with an international presence (offices in London and Birmingham). Founded in 2009 and headquartered at SCO 196-197, Sector 34-A, Chandigarh, they have delivered projects over 250 acres in Chandigarh, Mohali, Derabassi and Zirakpur.',
                'projects' => [
                    [
                        'title'           => 'GBP Crest',
                        'description'     => 'Ultra-luxury 3 & 4 BHK apartments near the Chandigarh-Ludhiana highway in Kharar with world-class amenities and lush green surroundings.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Kharar-Ludhiana Road, Kharar',
                        'city'            => 'Kharar',
                        'state'           => 'Punjab',
                        'total_units'     => 240,
                        'available_units' => 30,
                        'price_from'      => 7500000,
                        'price_to'        => 13500000,
                        'possession_date' => '2024-03-31',
                        'amenities'       => 'Rooftop Sky Lounge, Infinity Pool, Fully Equipped Gym, Squash Court, Landscaped Terrace, EV Charging',
                        'rera_id'         => 'PBRERA-SAS79-PR0612',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'GBP Eco Greens',
                        'description'     => 'Affordable eco-friendly housing project in Derabassi offering 2 & 3 BHK flats with modern amenities at competitive pricing.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Village Jharmari, Derabassi',
                        'city'            => 'Derabassi',
                        'state'           => 'Punjab',
                        'total_units'     => 320,
                        'available_units' => 22,
                        'price_from'      => 2900000,
                        'price_to'        => 4800000,
                        'possession_date' => '2024-06-30',
                        'amenities'       => 'Community Garden, Walking Trail, Kids Play Area, 24/7 Security, Power Backup, Ample Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0581',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 3. Motia Builders & Developers ─────────────────────────────
            [
                'name'                     => 'Hem Raj Mittal',
                'company_name'             => 'Motia Builders & Developers',
                'email'                    => 'info@motia.co.in',
                'phone'                    => '9988600600',
                'website'                  => 'https://www.motia.co.in',
                'city'                     => 'Zirakpur',
                'established_year'         => '2005',
                'rera_registration'        => 'PBRERA-SAS79-PR0445',
                'cities_operating'         => 'Zirakpur, Kharar, Kurali, Derabassi, Mohali',
                'total_delivered_projects' => 15,
                'rating'                   => 4.2,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Motia Builders & Developers was established in 2005 by Mr. Hem Raj Mittal, Labh Chand Mittal and Meshi Mittal. Operating since 2005, the group has delivered 15+ projects offering residential plots, commercial properties, and 3 & 4 BHK flats in Zirakpur, Kharar, Kurali, Derabassi and Mohali.',
                'projects' => [
                    [
                        'title'           => 'Motia Guildford Square',
                        'description'     => 'Premium 3 & 4 BHK luxury apartments on Airport Road, Zirakpur. Strategically located with excellent connectivity to Chandigarh International Airport and PR7 Highway.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'PR7 Airport Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 180,
                        'available_units' => 65,
                        'price_from'      => 8000000,
                        'price_to'        => 14500000,
                        'possession_date' => '2027-06-30',
                        'amenities'       => 'Clubhouse, Rooftop Pool, Gym, Concierge Services, Smart Home, 3-Level Parking, EV Charging',
                        'rera_id'         => 'PBRERA-SAS79-PR0445',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'Motia Gill Estate Kurali',
                        'description'     => 'Premium residential plots in a well-planned colony near Kurali with wide roads, excellent connectivity to Chandigarh Airport and Kharar Railway Station.',
                        'project_type'    => 'Plots',
                        'status'          => 'Ready to Move',
                        'address'         => 'Kurali, Near Kharar Railway Station',
                        'city'            => 'Kharar',
                        'state'           => 'Punjab',
                        'total_units'     => 350,
                        'available_units' => 40,
                        'price_from'      => 1800000,
                        'price_to'        => 4200000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Wide Internal Roads, Sewerage, Water Supply, Electrification, Boundary Wall, Security',
                        'rera_id'         => 'PBRERA-SAS79-PR0389',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 4. Motiaz Group ────────────────────────────────────────────
            [
                'name'                     => 'Pawan Bansal',
                'company_name'             => 'Motiaz Group',
                'email'                    => 'info@motiaz.com',
                'phone'                    => '7259372593',
                'website'                  => 'https://motiaz.com',
                'city'                     => 'Panchkula',
                'established_year'         => '1998',
                'rera_registration'        => 'PBRERA-SAS79-PR0312',
                'cities_operating'         => 'Panchkula, Zirakpur, Peer Muchalla, Dayalpura, Chandigarh',
                'total_delivered_projects' => 22,
                'rating'                   => 4.5,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Motiaz Group is a Panchkula-based luxury real estate developer with 25+ years of experience. Named in tribute to Shri Moti Ram Ji, the group delivers premium residential and commercial projects in Panchkula, Zirakpur and Peer Muchalla. Office: SCO 393, First Floor, Sector 8, Panchkula.',
                'projects' => [
                    [
                        'title'           => 'Motiaz Blue Ridge',
                        'description'     => 'Luxury 3 BHK apartments in the most prestigious location of Zirakpur with stunning views, premium finishes and world-class clubhouse facilities.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Peer Muchalla, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 200,
                        'available_units' => 18,
                        'price_from'      => 10500000,
                        'price_to'        => 18000000,
                        'possession_date' => '2024-09-30',
                        'amenities'       => 'Olympic Pool, Fully Equipped Gymnasium, Grand Clubhouse, Squash Court, Yoga & Meditation Centre, Amphitheatre, 3-Level Basement Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0312',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'Motiaz Royal Citi',
                        'description'     => 'Premium township on Delhi Highway, Zirakpur with 3 & 4 BHK apartments. Excellent connectivity to International Airport and Railway Station.',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Chandigarh-Ambala Highway, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 460,
                        'available_units' => 35,
                        'price_from'      => 6500000,
                        'price_to'        => 12000000,
                        'possession_date' => '2024-06-30',
                        'amenities'       => 'Clubhouse, Pool, Gym, Kids Park, Elderly Garden, 24/7 Security, Power Backup, Covered Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0288',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 5. Omaxe Ltd. ──────────────────────────────────────────────
            [
                'name'                     => 'Mohit Goel',
                'company_name'             => 'Omaxe Ltd.',
                'email'                    => 'customercare@omaxe.com',
                'phone'                    => '9216925999',
                'website'                  => 'https://www.omaxe.com',
                'city'                     => 'Chandigarh',
                'established_year'         => '1987',
                'rera_registration'        => 'PBRERA-SAS79-PR0180',
                'cities_operating'         => 'New Chandigarh (Mullanpur), Chandigarh, Mohali, Derabassi',
                'total_delivered_projects' => 38,
                'rating'                   => 4.0,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Omaxe Ltd. is one of India\'s leading real estate developers with 38 years of experience and presence in 31+ cities. In the Tricity, their flagship development is the Omaxe New Chandigarh township in Mullanpur — a 1000-acre integrated township at the foothills of the Shivalik Hills, just 8 km from Chandigarh.',
                'projects' => [
                    [
                        'title'           => 'Omaxe New Chandigarh Township',
                        'description'     => 'Flagship 1000-acre integrated township at Mullanpur, New Chandigarh. Offers plots, independent floors, apartments and villas in Phase 1, 2 and 3. Located 8 km from Chandigarh with 33% green belt.',
                        'project_type'    => 'Township',
                        'status'          => 'Under Construction',
                        'address'         => 'Mullanpur, New Chandigarh',
                        'city'            => 'Mullanpur',
                        'state'           => 'Punjab',
                        'total_units'     => 4500,
                        'available_units' => 800,
                        'price_from'      => 2500000,
                        'price_to'        => 25000000,
                        'possession_date' => '2027-12-31',
                        'amenities'       => 'Commercial Hub, Schools, Hospitals, Cricket Stadium, 200-Foot Road, Metro Connectivity, Amusement Park, 33% Green Belt',
                        'rera_id'         => 'PBRERA-SAS79-PR0180',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'Omaxe Gardenia',
                        'description'     => 'Luxury 3 BHK + 3+1 BHK apartments and penthouses with terrace gardens in New Chandigarh. An exclusive retreat for the discerning few.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'New Chandigarh, Mullanpur',
                        'city'            => 'Mullanpur',
                        'state'           => 'Punjab',
                        'total_units'     => 180,
                        'available_units' => 25,
                        'price_from'      => 7000000,
                        'price_to'        => 18000000,
                        'possession_date' => '2025-03-31',
                        'amenities'       => 'Private Terrace Gardens, Infinity Pool, Clubhouse, Concierge, Smart Home Automation, 5-Star Amenities',
                        'rera_id'         => 'PBRERA-SAS79-PR0192',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 6. DLF Limited ─────────────────────────────────────────────
            [
                'name'                     => 'Aakash Ohri',
                'company_name'             => 'DLF Limited',
                'email'                    => 'customercare@dlf.in',
                'phone'                    => '1800116622',
                'website'                  => 'https://www.dlf.in',
                'city'                     => 'Chandigarh',
                'established_year'         => '1946',
                'rera_registration'        => 'PBRERA-SAS79-PR0095',
                'cities_operating'         => 'Chandigarh, Mohali, Panchkula, Mullanpur',
                'total_delivered_projects' => 175,
                'rating'                   => 4.1,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'DLF Limited is India\'s largest real estate developer with 75+ years of experience. In the Tricity, DLF\'s marquee project is DLF Valley Panchkula (Sector 1-19) — a premium township offering independent villas, luxury floors and plots. DLF Hyde Park in South Mullanpur is another flagship luxury development.',
                'projects' => [
                    [
                        'title'           => 'DLF Valley Panchkula',
                        'description'     => 'Premium residential township in Panchkula Sectors 1-19 offering luxury independent floors, villas and plots. Nestled in lush green surroundings near the Shivalik Hills.',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 1-19, Panchkula',
                        'city'            => 'Panchkula',
                        'state'           => 'Haryana',
                        'total_units'     => 550,
                        'available_units' => 40,
                        'price_from'      => 12000000,
                        'price_to'        => 45000000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Club DLF, Swimming Pool, Tennis Courts, Gym, Jogging Track, Landscaped Gardens, Concierge, 24/7 Security',
                        'rera_id'         => 'PBRERA-SAS79-PR0095',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'DLF Hyde Park Bungalows',
                        'description'     => 'Ultra-luxury bungalows and independent houses in South Mullanpur on the Chandigarh Road. Exclusive lifestyle living just 1.7 km from New Chandigarh.',
                        'project_type'    => 'Villa',
                        'status'          => 'Ready to Move',
                        'address'         => 'South Mullanpur, Chandigarh Road',
                        'city'            => 'Mullanpur',
                        'state'           => 'Punjab',
                        'total_units'     => 315,
                        'available_units' => 20,
                        'price_from'      => 35000000,
                        'price_to'        => 75000000,
                        'possession_date' => '2025-06-30',
                        'amenities'       => 'Private Lawns, Grand Clubhouse, Golf Course View, Private Pool Option, Smart Home Systems, Concierge Service',
                        'rera_id'         => 'PBRERA-SAS79-PR0098',
                        'is_featured'     => true,
                    ],
                ],
            ],

            // ─── 7. Emaar MGF ───────────────────────────────────────────────
            [
                'name'                     => 'Amit Jain',
                'company_name'             => 'Emaar India',
                'email'                    => 'customercare@emaar.in',
                'phone'                    => '8800000008',
                'website'                  => 'https://www.emaar.in',
                'city'                     => 'Mohali',
                'established_year'         => '2005',
                'rera_registration'        => 'PBRERA-SAS79-PR0155',
                'cities_operating'         => 'Mohali, Chandigarh',
                'total_delivered_projects' => 12,
                'rating'                   => 4.2,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Emaar India is the Indian arm of Dubai-based Emaar Properties — one of the world\'s largest real estate companies. Their Mohali Hills development is one of the most prestigious master-planned townships in the Tricity, spanning Sectors 99–109 with residential plots, premium apartments and luxury villas.',
                'projects' => [
                    [
                        'title'           => 'Emaar Mohali Hills',
                        'description'     => 'Master-planned luxury township on Kharar-Banur Road spanning Sectors 99–109. Features residential plots, premium low-rise apartments and luxury villas in an integrated community.',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sectors 99-109, Kharar-Banur Road',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 2200,
                        'available_units' => 150,
                        'price_from'      => 8500000,
                        'price_to'        => 55000000,
                        'possession_date' => '2025-03-31',
                        'amenities'       => 'Golf Course, Club Emaar, Swimming Pool, Sports Complex, Schools, Retail High Street, Healthcare Facilities',
                        'rera_id'         => 'PBRERA-SAS79-PR0155',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'Emaar The Terraces',
                        'description'     => 'Premium low-rise luxury residences in Emaar Mohali Hills offering panoramic views and an exclusive lifestyle in a quiet, green environment.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Mohali Hills, Sector 104',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 1100,
                        'available_units' => 80,
                        'price_from'      => 9500000,
                        'price_to'        => 22000000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Private Terraces, Community Pool, Gym, Landscaped Greens, 24/7 Security, EV Charging, Smart Access',
                        'rera_id'         => 'PBRERA-SAS79-PR0158',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 8. Cascade Buildtech ───────────────────────────────────────
            [
                'name'                     => 'Vikram Sharma',
                'company_name'             => 'Cascade Buildtech',
                'email'                    => 'info@cascadebuildtech.com',
                'phone'                    => '9041904139',
                'website'                  => 'https://www.cascadebuildtech.com',
                'city'                     => 'Zirakpur',
                'established_year'         => '2010',
                'rera_registration'        => 'PBRERA-SAS79-PR0421',
                'cities_operating'         => 'Zirakpur, Mohali, Chandigarh, New Chandigarh',
                'total_delivered_projects' => 8,
                'rating'                   => 4.1,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Cascade Buildtech is a Tricity-based real estate company based near Airport Road, Zirakpur. They specialize in luxury 2, 3 and 4 BHK flats, penthouses in Mohali and Zirakpur, as well as commercial properties including SCO floors and retail spaces. Known for partnering with top builders to market their projects.',
                'projects' => [
                    [
                        'title'           => 'The Hermitage Park',
                        'description'     => 'Luxury 3 & 4 BHK apartments by Hermitage Infra in the heart of Mohali with resort-style amenities and stunning landscaping.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Airport Road, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 280,
                        'available_units' => 32,
                        'price_from'      => 9000000,
                        'price_to'        => 16000000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Resort Pool, Gym, Landscape Gardens, Yoga Deck, Club House, Smart Home, Multi-Level Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0421',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'The Medallion',
                        'description'     => 'Hallmark of luxury living in Mohali by Medalian Builders offering state-of-the-art premium apartments with sophisticated design.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Sector 82, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 160,
                        'available_units' => 70,
                        'price_from'      => 12000000,
                        'price_to'        => 24000000,
                        'possession_date' => '2026-12-31',
                        'amenities'       => 'Sky Lounge, Infinity Pool, Premium Gym, Concierge, Smart Home, EV Charging, Branded Lobby',
                        'rera_id'         => 'PBRERA-SAS79-PR0435',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 9. VCS Promoters & Developers ──────────────────────────────
            [
                'name'                     => 'Vikas Chopra',
                'company_name'             => 'VCS Promoters & Developers',
                'email'                    => 'info@vcsbuilders.com',
                'phone'                    => '9815074545',
                'website'                  => 'https://vcsbuilders.com',
                'city'                     => 'Mohali',
                'established_year'         => '2008',
                'rera_registration'        => 'PBRERA-SAS79-PR0502',
                'cities_operating'         => 'Mohali, Zirakpur, Chandigarh',
                'total_delivered_projects' => 9,
                'rating'                   => 4.3,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'VCS Promoters and Developers is a professional real estate company in Chandigarh Tricity offering residential and commercial projects in Mohali and Zirakpur. Their office is at Sector 74, Mohali. Known for transparent dealings and high-quality residential construction.',
                'projects' => [
                    [
                        'title'           => 'VCS One Mohali',
                        'description'     => 'Modern 3 & 4 BHK residential project in Sector 74, Mohali offering premium apartments with best-in-class construction quality and competitive pricing.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Sector 74, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 120,
                        'available_units' => 55,
                        'price_from'      => 6800000,
                        'price_to'        => 11500000,
                        'possession_date' => '2027-03-31',
                        'amenities'       => 'Club House, Swimming Pool, Gym, Power Backup, 24/7 Security, Children Play Area, Covered Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0502',
                        'is_featured'     => true,
                    ],
                ],
            ],

            // ─── 10. Gillco Builders ─────────────────────────────────────────
            [
                'name'                     => 'Gill Singh',
                'company_name'             => 'Gillco Builders & Promoters',
                'email'                    => 'info@gillcobuilders.com',
                'phone'                    => '9872600600',
                'website'                  => 'https://www.gillcobuilders.com',
                'city'                     => 'Mohali',
                'established_year'         => '2000',
                'rera_registration'        => 'PBRERA-SAS79-PR0325',
                'cities_operating'         => 'Mohali, Kharar, Chandigarh',
                'total_delivered_projects' => 14,
                'rating'                   => 4.2,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Gillco Builders & Promoters is one of the most trusted names in Mohali real estate with 24+ years of experience. Their flagship Gillco Parkhills project in Mohali is a well-known integrated township. The builder is known for timely delivery and quality construction.',
                'projects' => [
                    [
                        'title'           => 'Gillco Parkhills',
                        'description'     => 'Well-established gated township in Mohali offering 2, 3 & 4 BHK apartments with expansive green parks, sports facilities and strong community living.',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Kharar-Banur Road, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 1800,
                        'available_units' => 95,
                        'price_from'      => 4500000,
                        'price_to'        => 8500000,
                        'possession_date' => '2024-06-30',
                        'amenities'       => 'Parks, Walking Trails, Swimming Pool, Club House, Schools, Retail, Sports Complex, Power Backup, Security',
                        'rera_id'         => 'PBRERA-SAS79-PR0325',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'Gillco Valley',
                        'description'     => 'Residential plots and independent floors in Kharar with clear titles, wide roads and excellent connectivity to Chandigarh-Ludhiana Highway.',
                        'project_type'    => 'Plots',
                        'status'          => 'Ready to Move',
                        'address'         => 'Kharar, Near Chandigarh Road',
                        'city'            => 'Kharar',
                        'state'           => 'Punjab',
                        'total_units'     => 400,
                        'available_units' => 35,
                        'price_from'      => 2200000,
                        'price_to'        => 5000000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Gated Community, Wide Roads, Power Supply, Water Supply, Drainage, Parks, Security Gate',
                        'rera_id'         => 'PBRERA-SAS79-PR0341',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 11. ATS Homekraft ───────────────────────────────────────────
            [
                'name'                     => 'Getamber Anand',
                'company_name'             => 'ATS Homekraft',
                'email'                    => 'info@atshomekraft.com',
                'phone'                    => '9599330033',
                'website'                  => 'https://www.atshomekraft.com',
                'city'                     => 'Mohali',
                'established_year'         => '1998',
                'rera_registration'        => 'PBRERA-SAS79-PR0278',
                'cities_operating'         => 'Mohali, Chandigarh',
                'total_delivered_projects' => 32,
                'rating'                   => 4.0,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'ATS Homekraft is the affordable housing division of ATS Group, a well-known pan-India developer. Their ATS Golf Meadows project in Mohali is one of the most popular upcoming projects in Sector 115, adjacent to the Chandigarh Golf Range.',
                'projects' => [
                    [
                        'title'           => 'ATS Golf Meadows',
                        'description'     => 'Value-for-money residential project by ATS Group in Sector 115, Mohali adjacent to the Chandigarh Golf Range. Offering 2 & 3 BHK apartments at competitive pricing.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Sector 115, Adjacent to Golf Range, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 650,
                        'available_units' => 220,
                        'price_from'      => 5500000,
                        'price_to'        => 9800000,
                        'possession_date' => '2027-06-30',
                        'amenities'       => 'Golf Course Adjacent, Clubhouse, Swimming Pool, Gym, Yoga Deck, Jogging Track, Power Backup, 24/7 Security',
                        'rera_id'         => 'PBRERA-SAS79-PR0278',
                        'is_featured'     => true,
                    ],
                ],
            ],

            // ─── 12. Sushma Buildtech ────────────────────────────────────────
            [
                'name'                     => 'Pradeep Aggarwal',
                'company_name'             => 'Sushma Buildtech Ltd.',
                'email'                    => 'info@sushmabuildtech.com',
                'phone'                    => '9914014888',
                'website'                  => 'https://www.sushmabuildtech.com',
                'city'                     => 'Zirakpur',
                'established_year'         => '2002',
                'rera_registration'        => 'PBRERA-SAS79-PR0362',
                'cities_operating'         => 'Zirakpur, Chandigarh, Mohali, Patiala',
                'total_delivered_projects' => 16,
                'rating'                   => 4.2,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Sushma Buildtech is a Zirakpur-based real estate developer known for mid-segment and affordable housing. Their projects are registered with Punjab RERA and known for timely delivery. Operating in Zirakpur, Mohali, Chandigarh and Patiala with 16+ delivered projects.',
                'projects' => [
                    [
                        'title'           => 'Sushma Crescent',
                        'description'     => 'Affordable 2 & 3 BHK apartments in Zirakpur offering modern amenities and excellent connectivity to Chandigarh and the Airport. Ideal for first-time homebuyers.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'VIP Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 350,
                        'available_units' => 28,
                        'price_from'      => 3800000,
                        'price_to'        => 6500000,
                        'possession_date' => '2024-09-30',
                        'amenities'       => 'Clubhouse, Swimming Pool, Gym, 24/7 Security, Power Backup, Kids Play Area, Covered Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0362',
                        'is_featured'     => false,
                    ],
                    [
                        'title'           => 'Sushma Grande',
                        'description'     => 'Premium 3 & 4 BHK residential project in Zirakpur with high-end finishes and resort-style amenities for luxury living.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Airport Road, Zirakpur',
                        'city'            => 'Zirakpur',
                        'state'           => 'Punjab',
                        'total_units'     => 200,
                        'available_units' => 85,
                        'price_from'      => 7200000,
                        'price_to'        => 13000000,
                        'possession_date' => '2027-03-31',
                        'amenities'       => 'Rooftop Pool, Grand Clubhouse, Gym, Smart Home Features, EV Charging, 4-Level Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0378',
                        'is_featured'     => true,
                    ],
                ],
            ],

            // ─── 13. Hero Homes ──────────────────────────────────────────────
            [
                'name'                     => 'Rahul Munjal',
                'company_name'             => 'Hero Homes',
                'email'                    => 'info@herohomes.in',
                'phone'                    => '8800888083',
                'website'                  => 'https://www.herohomes.in',
                'city'                     => 'Mohali',
                'established_year'         => '2017',
                'rera_registration'        => 'PBRERA-SAS79-PR0558',
                'cities_operating'         => 'Mohali, Ludhiana, Gurugram',
                'total_delivered_projects' => 5,
                'rating'                   => 4.4,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Hero Homes is the real estate arm of the Hero Group — one of India\'s most trusted brands. Their flagship project Hero Homes Mohali in Sector 88A offers premium 2, 3 & 4 BHK apartments with world-class amenities, backed by the Hero Group\'s heritage of trust.',
                'projects' => [
                    [
                        'title'           => 'Hero Homes Mohali',
                        'description'     => 'Premium residential township by the Hero Group in Sector 88A, Mohali. Offering 2, 3 & 4 BHK apartments in a gated, amenity-rich campus near the city centre.',
                        'project_type'    => 'Residential',
                        'status'          => 'Under Construction',
                        'address'         => 'Sector 88A, SAS Nagar',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 1200,
                        'available_units' => 380,
                        'price_from'      => 6200000,
                        'price_to'        => 14000000,
                        'possession_date' => '2027-12-31',
                        'amenities'       => 'Grand Clubhouse, Swimming Pool, Gym, Tennis Court, Badminton Court, Walking Trail, Kids Zone, Smart Home, EV Charging, 24/7 Security',
                        'rera_id'         => 'PBRERA-SAS79-PR0558',
                        'is_featured'     => true,
                    ],
                ],
            ],

            // ─── 14. JLPL Group ──────────────────────────────────────────────
            [
                'name'                     => 'Jagdish Lal Pahwa',
                'company_name'             => 'JLPL Group',
                'email'                    => 'info@jlplgroup.com',
                'phone'                    => '9988011111',
                'website'                  => 'https://www.jlplgroup.com',
                'city'                     => 'Mohali',
                'established_year'         => '1987',
                'rera_registration'        => 'PBRERA-SAS79-PR0210',
                'cities_operating'         => 'Mohali, Zirakpur, Panchkula',
                'total_delivered_projects' => 25,
                'rating'                   => 4.0,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'JLPL Group is a pioneering real estate developer in Mohali with 37+ years of experience. They were among the first to develop Sector 82, Mohali — now the industrial heart of the city. JLPL Galaxy Heights is their popular residential project; JLPL Sanawar Hills is their premium hill station offering near Kasauli.',
                'projects' => [
                    [
                        'title'           => 'JLPL Galaxy Heights',
                        'description'     => 'Flagship residential towers in JLPL Industrial Area, Sector 82, Mohali. Premium 2, 3 & 4 BHK apartments in one of Mohali\'s most connected locations.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 82, JLPL Industrial Area, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 500,
                        'available_units' => 45,
                        'price_from'      => 5500000,
                        'price_to'        => 10000000,
                        'possession_date' => '2024-03-31',
                        'amenities'       => 'Club House, Swimming Pool, Gym, Badminton Court, Tennis Court, Landscaped Gardens, Power Backup, Security',
                        'rera_id'         => 'PBRERA-SAS79-PR0210',
                        'is_featured'     => true,
                    ],
                    [
                        'title'           => 'JLPL Falcon View',
                        'description'     => 'Luxury high-rise residential towers in Mohali with unobstructed views. Premium 3 & 4 BHK apartments with high-end finishes and exclusive club facilities.',
                        'project_type'    => 'Residential',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 66A, Mohali',
                        'city'            => 'Mohali',
                        'state'           => 'Punjab',
                        'total_units'     => 300,
                        'available_units' => 28,
                        'price_from'      => 9500000,
                        'price_to'        => 18500000,
                        'possession_date' => '2024-09-30',
                        'amenities'       => 'Helipad, Infinity Pool, Gymnasium, Sky Lounge, Concierge, Smart Home, EV Charging, 4-Level Parking',
                        'rera_id'         => 'PBRERA-SAS79-PR0225',
                        'is_featured'     => false,
                    ],
                ],
            ],

            // ─── 15. Ansal API ───────────────────────────────────────────────
            [
                'name'                     => 'Deepak Ansal',
                'company_name'             => 'Ansal API',
                'email'                    => 'customercare@ansalapi.com',
                'phone'                    => '9810009100',
                'website'                  => 'https://www.ansalapi.com',
                'city'                     => 'Panchkula',
                'established_year'         => '1967',
                'rera_registration'        => 'PBRERA-SAS79-PR0145',
                'cities_operating'         => 'Panchkula, Mohali, Chandigarh, Ambala',
                'total_delivered_projects' => 88,
                'rating'                   => 3.9,
                'is_verified'              => true,
                'status'                   => 'active',
                'description'              => 'Ansal API is one of India\'s oldest and most established real estate groups with 57+ years of experience. In the Tricity, they are active in Panchkula and Mohali with multiple residential townships. Known for affordable housing and well-planned colonies.',
                'projects' => [
                    [
                        'title'           => 'Ansal Orchard County Panchkula',
                        'description'     => 'Well-planned residential township in Panchkula by Ansal API offering 2 & 3 BHK apartments, independent floors and plots. Popular with families for its strategic location.',
                        'project_type'    => 'Township',
                        'status'          => 'Ready to Move',
                        'address'         => 'Sector 19, Panchkula',
                        'city'            => 'Panchkula',
                        'state'           => 'Haryana',
                        'total_units'     => 800,
                        'available_units' => 55,
                        'price_from'      => 4200000,
                        'price_to'        => 9500000,
                        'possession_date' => '2024-12-31',
                        'amenities'       => 'Community Club, Swimming Pool, Gym, Parks, Schools, Shopping Complex, 24/7 Security, Power Backup',
                        'rera_id'         => 'PBRERA-SAS79-PR0145',
                        'is_featured'     => false,
                    ],
                ],
            ],

        ];
    }
}
